# m1-live-findings.md — M1 실기동 검증 기록 (2026-07-16)

> M0 정찰(`recon-findings.md`)은 사람이 수동으로 UI를 조작하며 관찰한 기록이었다. 이 문서는
> **실제 구현체(`acquire/`)를 조교 계정으로 돌리며** 얻은 관측이다. 정찰 문서의 추정 중 일부가
> 여기서 틀린 것으로 확인됐다 — 그 정정만 정리한다. 성공한 부분은 코드 자체가 증거이므로 여기선
> **실패·정정 사항 위주**로 적는다.

- 실기동 대상: 3분반 `band_no=103239777`, 조교 계정(김태훈), test 모드, 기간 2026-06-28~2026-07-16
- 사용 도구: `npm start`(=`electron .`) + `BSC_DEVTOOLS=1` 환경변수로 DevTools 강제 오픈 + 사용자가 직접 Network/Console 확인

---

## 1. 확인된 것 (정상 동작 — 코드 그대로 유지)

| 항목 | 결과 |
|---|---|
| `input/1_설정.xlsx` 부트스트랩·검증 | 정상. 노란칸 미기입 시 템플릿 생성 후 중단, production 모드 날짜 강제 등 전부 실측 확인 |
| Electron `persist:` 세션 재사용 | 정상. 최초 1회만 수동 로그인(2FA 포함) 필요, 이후 재기동 시 자동 인증됨(로그인 대기 없이 `authOk` 즉시 도달) |
| `win.loadURL()`의 `ERR_ABORTED` | 정상 동작임이 확인됨(로그인 리다이렉트 체인 때문). `acquire/collector.js`의 `safeLoadURL`이 이미 이 케이스를 흡수함 — **손대지 말 것** |
| 피드 백필(`get_posts_and_announcements`) | 완전 동작. `next_params:null`까지 정상 소진, 27건 전량 캡처, `created_at` epoch ms → KST 변환도 recon 실측치와 일치 |
| raw append + dedup(`acquire/writer.js`) | 정상. 재기동 시 기존 파일 스캔해 dedup 인덱스 복원, 중복 라인 안 쌓임 |
| 게시글 상세 모달 오픈 트리거 | **`win.loadURL(post.web_url)` 같은 하드 네비게이션이 아니라, 피드 화면에 이미 렌더링된 `<a class="text" href=".../post/<postNo>">`(작성자명 링크)를 찾아 `.click()`하면 모달이 뜬다.** `acquire/collector.js`의 `openPostModal()`이 이 방식으로 구현되어 있고 실측으로 확인됨(사용자가 직접 화면에서 모달이 열려 댓글이 스크롤되는 것까지 목격) |
| 모달 닫기 버튼 | `.btnCloseLyPost` (class). 단, 이 요소가 **모달이 안 열린 상태에서도 DOM에 이미 존재할 가능성**이 있어(§3 참조) `document.querySelector('.btnCloseLyPost')`의 존재 여부만으로 "모달이 열렸다"고 판단하면 안 됨 — 다음 세션에서 가시성(`offsetParent`, bounding rect, 혹은 CDP로 실제 응답이 왔는지)까지 같이 확인하도록 고칠 것 |

## 2. 🚨 핵심 실패: 댓글(`get_comments`) 응답이 캡처 안 됨

### 2-1. 증상
- 게시글 클릭 → 모달이 뜨고 **화면에는 댓글이 정상적으로 렌더링됨**(사용자가 직접 확인: 전석훈 글 댓글 10개, 김희승 글 댓글 9개, 마지막 댓글자·대댓글까지 스크롤로 확인).
- 그런데 `acquire/collector.js`의 `collectCommentsForPost()`는 3회 재시도(약 25~30초) 후에도 `commentPage` 이벤트를 못 받고 포기함.
- DevTools Network 탭에서 직접 확인한 결과, 요청은 **실제로 발생**한다:
  ```
  GET https://api-kr.band.us/v2.3.0/get_comments?ts=<epoch>&band_no=103239777&content_key=%7B%22content_type%22%3A%22post%22%2C%22post_no%22%3A27%7D&resolution_type=4
  ```
  (recon-findings §1이 예측한 그대로의 URL·파라미터 — 엔드포인트 패턴 자체는 정확함)

### 2-2. 원인 규명 과정 (이후 세션이 재확인할 필요 없도록 상세 기록)
1. `XMLHttpRequest.prototype.send.toString()`를 콘솔에서 확인 → **우리 preload가 심은 패치 코드가 정확히 그대로 설치되어 있음**(`acquire/preload.js`의 XHR 패치 소스와 문자 그대로 일치).
2. `typeof window.__bandCaptureSend` → `'function'` (contextBridge 노출도 정상).
3. `window.__bandCaptureSend`를 래핑해 호출 여부를 로깅하도록 콘솔에서 몽키패치 → **게시글 클릭 후 단 한 번도 로그가 안 찍힘**. 즉 `XHRProto.send` 패치의 `if (info && isDataHost(info.url))` 조건까지 코드가 도달하지 않거나, `info`(=`this.__bandCapture`, `.open()`에서 설정)가 비어있는 상태로 `.send()`가 호출된다는 뜻.
4. Network 탭의 **Initiator(요청 호출 스택)** 를 확인 → `ajax` → `__send` → `Deferred`/`fireWith`(jQuery류 패턴) → `getCommentList` → `fetchCommentList` → `fetchLastCommentList` → `_fetchFirstViewCommentList` → ... → `_onClickPostItem` → `_showPostDetailLayer` 로 이어지는 **band.us 자체 내부 HTTP 클라이언트 래퍼**(변수명 `XHRProto`로 표시됨, boot.bundle.js 내부)를 통해 요청이 나감.

### 2-3. 결론(가설, 확인 필요)
band.us의 부트스트랩 번들이 초기 로드 시점에 **원본 XHR `open`/`send` 참조를 이미 캡처해 자체 `XHRProto`/`ajax` 래퍼에 고정**해두고, 댓글 조회처럼 특정 코드 경로(`getCommentList` 계열)는 그 캡처된 참조를 재사용하는 것으로 보인다. 반면 피드·게시글 상세·멤버 목록은 (아마 다른 코드 경로라) 정상적으로 우리 패치를 통과했다. **preload 시점에 실행되는 `webFrame.executeJavaScript` 몽키패치가 "페이지 스크립트보다 먼저 실행된다"는 Electron의 일반 보장이, band.us의 극초기 부트스트랩 코드(어쩌면 프리로드보다도 먼저 평가되는 인라인 스크립트)에 대해서는 100% 보장되지 않는 것으로 추정.** 정확한 코드 위치까지는 못 밝혔고(boot.bundle.js는 난독화/압축됨), 밝힐 필요도 없다 — **몽키패치 방식 자체를 CDP로 바꾸면 이 문제가 근본적으로 사라진다**(§ `m1-cdp-migration-plan.md` 참조).

### 2-4. 참고: 미분류 호출 디버그 로그
`acquire/capture/interceptor.js`에 임시로 추가한 디버그 로그(`분류 안 되는 data-host 호출` 로그)로 확인한 결과, band.us 페이지 로드 시 아래와 같은 다수의 부트스트랩 API 호출이 있음(전부 `get_comments`와 무관, `endpoints.js`에서 의도적으로 미분류 처리 중인 정상 노이즈):
`get_band_information`, `get_env`, `get_profile`, `get_user_config`, `get_default_profile_set`, `get_my_languages`, `get_target_language`, `get_content_creation_punishment_info`, `get_band_list_with_filter`, `get_news_count`, `touch_band_access`, `get_ongoing_missions`, `get_recently_ended_missions`, `get_reserved_post_count`, `get_my_approvable_post_count`, `get_band_notices`, `get_hashtags`, `get_updated_members`, `get_band_service_guide`, `get_upcoming_schedules`, `get_photos`, `get_page_links`, `get_chat_channels`, `get_open_chat_channels`, `get_files`, `get_member_groups`, `get_members_of_band_with_filter`.
**`bapi-kr.band.us/v2.0.0/batch` 호출은 이번 실측에서 한 번도 안 잡혔다** — recon-findings가 언급한 배치 호출은 최소 이 시나리오(피드 진입 직후)에서는 안 쓰이거나, 우리 캡처망이 이미 원천적으로 놓치고 있는 것(§2-3의 원인과 동일 계열일 가능성)일 수 있음. CDP 전환 후 재확인 필요.

## 3. 아직 못 밝힌 것 (CDP 전환 후 재확인 대상)

- **`.btnCloseLyPost` 존재만으로 "모달 열림"을 판단하는 게 맞는지.** 같은 클릭에 대해 어떤 실행에서는 "모달 열림"으로, 어떤 실행에서는 "모달 안 열림"으로 나왔다 — 판단 로직(존재 여부만 체크, 가시성 미체크) 자체가 불안정할 가능성이 있음.
- **"이전 댓글 더보기"/대댓글 로드 버튼의 정확한 selector.** `acquire/collector.js`의 `clickLoadMoreComments()`는 텍스트 매칭(`이전\s*댓글|댓글\s*더\s*보기|...`)으로 방어적으로 구현했지만 실측 검증 전. CDP로 응답이 잡히기 시작하면 이 트리거가 실제로 추가 페이지를 불러오는지 바로 확인 가능.
- **멤버 목록 페이지 URL.** `https://www.band.us/band/<id>/member`는 band.us 관행을 따른 추정치, 실측 확인 안 됨.
- **대댓글(`content_type:"comment"`) 조회의 정확한 파라미터.** 여태 댓글 자체가 안 잡혀서 확인할 기회가 없었음.

## 4. 이번 세션에서 반복하지 말아야 할 것

- **짧은 시간에 반복적으로 `electron .`을 재기동하지 말 것.** 이번 세션에서 약 11회 재기동했고, 한 번은 로그인이 30초 넘게 안 뜨는(타임아웃) 상황도 있었다 — band.us/naver 쪽 anti-abuse에 걸릴 위험이 실재한다. 실기동 검증은 **한 번에 여러 가설을 모아 검증**하고, 재기동 사이 최소 몇 분 간격을 두는 식으로 진행할 것.
- **`win.loadURL(post.web_url)`로 게시글 상세를 열려는 시도를 재검증하지 말 것.** 이미 3개 포스트(27·26·25)로 반복 확인했고 명확히 실패함(§ recon-findings §8의 "상세뷰 자동 인라인 로드" 추정은 틀렸다 — 사람이 클릭한 UX였지 하드 네비게이션이 아니었다). `openPostModal()`의 클릭 방식만 사용할 것.

## 5. CDP 전환(2026-07-16, 후속 세션) — preload → CDP로 바꾸며 겪은 실패들

`doc/m1-cdp-migration-plan.md`대로 preload 몽키패치를 CDP(`webContents.debugger`)로 바꾸는 과정에서
아래 문제들을 실기동으로 순서대로 겪고 고쳤다. 다음에 CDP 캡처 코드를 건드릴 때 같은 삽질을
반복하지 않도록 기록한다 (구현은 `acquire/capture/cdp-capture.js` 상단 주석에도 요약돼 있음).

- **`dbg.attach('1.3')`처럼 구식 프로토콜 버전을 넘기면 안 됨.** Electron 31에서 이후
  `sendCommand`가 응답 없이 멈춰(`Network.enable`이 영원히 pending) `win.loadURL()`까지
  진행이 안 되고 창이 흰 화면으로 무한정 멈췄다. 인자 없이 `dbg.attach()`만 호출할 것.
- **CDP attach를 기다린 뒤 탐색을 시작하면 안 됨.** attach/enable이 느리거나(위 항목처럼) 막히면
  로그인 화면 자체가 안 뜬다. `acquire/main.js`는 `attachCdpCapture(...)`를 `await` 없이
  던져두고 `collector.runBandCollection(...)`을 바로 시작하도록 짜여 있다 — 이 순서를 되돌리지
  말 것.
- **`Network.getResponseBody`는 이 앱 트래픽에서 100% 실패했다** (`No resource with given
  identifier found`, 타이밍과 무관하게 항상). `Fetch.enable({patterns, requestStage:'Response'})`
  로 응답을 실제로 일시정지시킨 뒤 그 자리에서 `Fetch.getResponseBody`로 읽고
  `Fetch.continueResponse`로 흘려보내는 방식만 안정적으로 동작했다.
- **`Fetch.enable`만 켜면 바디가 항상 빈 문자열(len=0)이었다.** `Network.enable`을
  `{maxTotalBufferSize, maxResourceBufferSize}`를 명시해서 같이 켜야 실제로 바디가 채워졌다
  (버퍼 크기 인자 없이 `Network.enable()`만 호출하면 사실상 버퍼가 0인 것으로 보임).
  이 둘을 반드시 같이 켤 것.
- **응답은 gzip으로 온다.** `Fetch.getResponseBody`가 압축 해제를 안 해주므로
  `content-encoding` 헤더를 보고 직접 `zlib.gunzipSync` 등으로 풀어야 한다.
- **data-host URL은 CORS preflight(OPTIONS)에도 그대로 걸려서 매 요청마다 캡처가 두 번 온다.**
  첫 번째(len=0)는 preflight, 두 번째가 실제 데이터 — `interceptor.js`는 빈 바디를 조용히
  무시하도록 되어 있으니 정상이다. "빈 바디 캡처가 자꾸 보인다"고 다시 놀라지 말 것.
- **CDP 캡처는 preload보다 훨씬 빨라서(수백 ms) `collector.js`의 기존 "클릭 → randomDelay →
  그제서야 리스너 등록" 순서가 이벤트를 영영 놓치는 레이스가 됐다.** 클릭 유발 전에 리스너부터
  걸어야 한다는 원칙만으로는 호출부마다 다 고치기 번거로워서, `interceptor.js`가 최근 이벤트를
  60초간 버퍼링해두고(`takeRecent`) `collector.js`의 `waitForEvent`가 새 리스너를 걸기 전에
  먼저 그 버퍼를 확인하도록 바꿨다. 앞으로 새 이벤트 대기 지점을 추가할 때도 `waitForEvent`를
  통해서만 기다리면 이 보호를 자동으로 받는다.
- **피드 DOM 가상화로 `openPostModal`이 "not-found"를 자주 뱉는 문제(§3)는 CDP와 무관한
  기존 문제였다** — CDP 전환 전 로그(오늘 세션 앞부분)에도 동일 패턴(post_no=22~17 연속
  not-found)이 이미 있었다. 이걸 근본적으로 우회하기 위해 피드 스크롤 기반 순회를 버리고,
  **모달 안의 이전/다음 글 화살표**(`.btnNextPost`=과거 방향, `.btnPrevPost`=최신 방향 — 사용자
  실측 확인. 가장 최신 글엔 `.btnPrevPost`가, 가장 오래된 글엔 `.btnNextPost`가 없음)로 넘기는
  구조(`walkPostsViaModal`)로 재작성했다. 피드에서 가장 최신 글 링크 하나만 찾아 클릭하면 되고,
  이후로는 피드 DOM 상태와 완전히 무관하게 순회할 수 있다.
  - **1차 실기동에서 버그 발견·수정**: `clickNextPost`가 `btn.offsetParent === null`로 가시성을
    확인했는데, `.btnNextPost`가 `position:fixed` 오버레이라서 화면에 보여도 `offsetParent`가
    `null`이 나와 첫 글(post_no=47)부터 "버튼 없음(가장 오래된 글)"으로 오판, 순회가 1건만
    처리되고 즉시 종료됐다. **존재 여부만**(`document.querySelector('.btnNextPost')`가 null인지)
    확인하도록 고침 — `offsetParent`/가시성 체크를 이 버튼에 다시 추가하지 말 것.
  - **아직 실기동으로 검증 못함(다음 세션 최우선 확인 사항)**: 위 수정 반영 후 `.btnNextPost`
    클릭이 실제로 여러 글에 걸쳐 정상적으로 다음 글로 넘어가는지, 그리고 클릭마다 새
    `get_post` 캡처(`postDetail` 이벤트)가 오는지(캐시된 인접 글을 재사용해 네트워크 호출이
    안 나갈 가능성 있음). §6 참조.

## 6. 다음 세션 시작 지점 (2026-07-16 세션 종료 시점)

**직전에 한 일**: `clickNextPost`의 `offsetParent` 오판 버그를 고쳤다(`acquire/collector.js`).
`node --check` 통과 확인함. **아직 실기동 검증 전** — 이 상태에서 세션이 종료됐다.

**다음 세션이 할 일 (순서대로)**:
1. `npx electron .`로 1회 실행(세션 persist라 재로그인 불필요할 가능성 높음 — 필요하면 사람이
   직접 로그인).
2. `logs/audit/`의 최신 로그 파일을 확인해:
   - `[collector] 모달 순회: post_no=... 이후 다음 글 버튼 없음` 로그가 **1건 처리 직후 바로**
     뜨면 아직도 버그가 있다는 뜻(§5 참조) — 재검증 필요.
   - 여러 `post_no`에 걸쳐 정상적으로 이동하며 `[collector] post_no=...: 댓글 API 응답을...`
     류 로그 없이(=제때 캡처됨) 진행되면 성공.
   - `data/raw/103239777/<날짜>/items.ndjson`에 `"schemaType":"comment"` 레코드가 여러
     post_no에 걸쳐 쌓이는지 `grep '"schemaType":"comment"'`로 확인.
3. 성공하면: `postsCommentsComplete`/`postsRepliesIncomplete` 수치로 대댓글(§3의 selector
   미확정 이슈)까지 완전히 도는지 확인. 대댓글이 계속 미완료로 남으면 `clickLoadMoreComments`의
   텍스트 매칭 selector를 재검증할 차례(모달이 열려있는 지금은 CDP로 실제 요청 발생 여부를
   바로 볼 수 있으니 진단이 쉬움).
4. **재기동 최소화 원칙(§4)을 지킬 것** — 오늘 세션에서 이미 15회 이상 재기동했다. 이번엔
   가설을 최대한 모아 한 번에 검증할 것.

**읽을 순서**: 이 파일(§5~6) → 필요하면 `doc/m1-cdp-migration-plan.md` → 코드는
`acquire/collector.js`(특히 `walkPostsViaModal`/`clickNextPost`)와
`acquire/capture/cdp-capture.js` 상단 주석.

## 7. 세 번째 세션(2026-07-16 계속) — 답글 캡처는 해결, 상위 페이지네이션 잔여 문제

§5~6의 `clickNextPost` 버그를 고친 뒤 실기동하며 두 가지를 더 발견·수정했다(이번엔 AI가 사용자
승인 하에 직접 `npx electron .`을 실행하며 CDP 캡처 로그만으로 진단했다 — §8 참고).

- **`.closest()` 자기 자신 매칭 버그**: `clickLoadMoreComments`가 `closeBtn.closest('[class*="ly" i]')`로
  모달 스코프를 구했는데, `closeBtn` 자신의 클래스 `btnCloseLyPost`에 이미 "Ly"가 들어있어 자기 자신이
  매칭되어버렸다(`.closest()`는 자신부터 검사). 그 결과 스코프가 닫기 버튼 자신(leaf)이 되어 버튼 탐색이
  항상 빈 배열이었다. `closeBtn.parentElement`부터 시작하도록 고침.
- **답글은 클릭이 아니라 임베드 데이터였다**: `_commentCountBtn`("댓글N")를 답글 펼치기 버튼으로 추정하고
  클릭 루프를 만들었으나, `BSC_DEBUG_UNCLASSIFIED=1`로 미분류 호출까지 다 찍어봐도 클릭이 네트워크 요청을
  전혀 안 만들었다. 나중에 기존 캡처 데이터를 다시 보니 최상위 댓글 응답(`get_comments?content_type=post`)의
  각 댓글 객체에 이미 `latest_comment` 배열로 최근 답글이 내려오고 있었다 — `_commentCountBtn`은 사실
  댓글 하나의 답글 개수가 아니라 **게시글 전체 댓글 수 배지**였던 것으로 보인다(`.postCount`/`.postCountLeft`/
  `.faceComment`와 값이 항상 동일했음). `interceptor.js`가 `latest_comment`를 파싱해 클릭 없이 기록하도록
  바꿨고, 이 반 데이터는 대부분 댓글당 답글이 1개뿐이라(교사 답글 패턴으로 추정) 그걸로 실측
  `postsRepliesIncomplete: []`까지 나왔다. 클릭 기반 답글 루프는 완전히 제거했다(효과가 없었고 글당
  최대 2분을 낭비했다 — 체감 속도 저하의 주범이었다).
- **답글 dedup 충돌 버그**: 답글의 `comment_id`는 부모 스레드마다 로컬로 재시작하는 번호라(전역 유일
  아님), `writer.js`가 `comment_id`만으로 dedup하면 서로 다른 부모의 답글끼리 ID가 겹쳐 조용히
  유실될 수 있었다. `parentCommentId:comment_id` 복합키로 바꿨다.
- **부분 실패가 조용히 샜다**: 상위 댓글 페이지네이션이 일부만 받고 멈춘 경우(`sawAny=true`인데
  `topLevelDone=false`) 경고를 안 찍던 버그를 고쳐서, 이제 `postsCommentsComplete` 미달과 경고 개수가
  항상 일치한다.

### 7-1. 아직 안 풀린 문제: 상위 댓글("이전 댓글") 페이지네이션이 일부 글에서 멈춤

마지막 실기동(2026-07-16 23:49~23:55 KST) 기준 `postsCommentsComplete: 39/47` — 8개 글이 미완료.
로그에 경고가 뜬 건 `post_no=48`(comment_count 11→14→16으로 세션마다 달랐음 — 실시간으로 학생들이
계속 댓글 다는 중인 글)과 `post_no=4`(comment_count=14) 둘뿐이었다(위 부분-실패 버그 수정 전이라
나머지 6개는 경고 없이 새어나간 것으로 추정 — 다음 실기동에서 경고 개수로 재확인 필요).

둘 다 교수님 과제글이 아니라 일반 학생 글이었다(post_no=4 작성자 윤배희, post_no=48 작성자 강민지) —
예외 대상이 아니므로 진짜 결손이다.

## 8. 다음 세션 전 넓게 생각해본 것: 원인 가설과 더 나은 디버깅 방식

### 8-1. 상위 페이지네이션 멈춤의 원인 가설 (확신도 순)

1. **(유력) 페이지네이션 도중 목록이 실시간으로 변한다.** `post_no=48`은 세 번의 실기동에서
   `comment_count`가 11→14→16으로 계속 늘었다 — 즉 우리가 그 글의 댓글을 순회하는 동안에도 실제
   학생들이 계속 댓글을 달고 있었다는 뜻이다. `이전 댓글` 페이지네이션이 cursor/offset 기반이라면,
   맨 위에 새 댓글이 계속 삽입되는 상황에서 커서가 밀리거나 무효화될 수 있다. 밴드 프론트엔드가 이걸
   "새 댓글 N개 — 새로고침" 같은 배너로 처리하며 조용히 자동 갱신을 멈추는 UX일 가능성이 있다. 이
   가설이 맞다면 **활발히 댓글이 달리는 글은 그 활동이 잦아든 뒤(수업 시간 이후)에 수집하는 편이
   근본적으로 더 안전하다** — 코드를 더 고치기보다 수집 타이밍 자체를 조정하는 게 답일 수 있다.
2. **(가능) 세션 내 첫 댓글 요청의 콜드스타트.** `post_no=48`은 항상 그 세션에서 가장 최신 글이라
   `walkPostsViaModal`이 매번 제일 먼저 여는 글이다 — 즉 "항상 실패"가 "항상 첫 시도"와 우연히
   겹쳤을 수 있다. CDP `Fetch.enable` 일시정지 파이프라인이 세션 내 특정 "종류"의 첫 요청에서만
   미묘하게 느릴 가능성(도메인 웜업)이 있다. `post_no=4`처럼 첫 글이 아닌데도 실패하는 사례가 있어
   이것만으로는 전체를 설명 못 한다 — 첫 글 가설과 아래 3번(단순 확률적 플레이크)이 같이 작용할 수 있음.
3. **(가능) 페이싱을 0.3~2초로 낮춘 부작용.** 예전(1.5~4초)엔 이 정도로 자주 멈추지 않았을 수 있다
   (다만 예전에도 고댓글수 글에서 간헐적으로 멈췄으니 완전히 새로운 현상은 아님 — §5-1). 클릭 간격이
   짧아지면 밴드 프론트엔드가 이전 클릭의 렌더링/상태 업데이트를 채 끝내기 전에 다음 클릭을 받을
   가능성이 커진다. 검증법: 댓글 수집 구간만 선택적으로 지연을 늘려(다른 구간은 그대로 두고) 실패율이
   줄어드는지 A/B로 비교.
4. **(가능성 낮음, 배제 안 됨) 세션 누적 피로/속도 제한.** 오늘 하루 20회 넘게 재기동했다 —
   band.us/네이버 쪽에서 이 계정·세션에 대해 특정 API(`get_comments`)만 조용히 골라 스로틀링하고
   있을 가능성을 완전히 배제할 수 없다. 이게 맞다면 원인은 코드가 아니라 "오늘 이 계정을 너무 많이
   썼다"이고, 며칠 뒤 재시도해서 실패율이 자연히 낮아지는지 보는 것 자체가 검증 방법이다.

### 8-2. 오늘 디버깅 방식의 한계와 다음엔 이렇게

오늘은 "가설 하나 → 코드 수정 → 재기동 → 로그 확인 → 다음 가설"을 7번 반복했다. 매 사이클이
로그인 대기+전체 순회(수 분)를 다시 태우는 비싼 루프였고, 무엇을 로그로 남길지 매번 재기동 전에
미리 추측해야 했다(추측이 틀리면 그 사이클 전체가 낭비). 다음엔 이렇게 바꾸는 게 낫다:

- **"많이 가볍게 재기동" 대신 "한 번을 두껍게 계측".** 다음 실기동 전에 `interceptor.js`에 상시
  옵션(env var, 예: `BSC_TRACE=1`)으로 **모든** data-host 요청의 생명주기(URL, kind, 요청 시각,
  응답 시각, 걸린 시간, 성공/실패/타임아웃)를 `logs/trace/`에 ndjson으로 통째로 남기는 기능을 미리
  넣어두면, 그 다음엔 실패 사례가 나올 때마다 재기동하지 않고 파일을 오프라인으로 여러 각도에서
  다시 분석할 수 있다. 오늘처럼 "이 가설을 확인하려면 뭘 로그로 남겨야 하지?"를 매번 재기동 전에
  추측할 필요가 없어진다.
- **"응답을 못 받음"과 "요청 자체가 안 나감"을 구분할 방법이 지금 없다.** 지금은 `commentPage`
  이벤트가 안 오면 그냥 "재시도 후 포기"만 하지, CDP `Network.requestWillBeSent` 레벨에서
  `get_comments` 요청이 애초에 발생했는지조차 기록하지 않는다. 이걸 별도로 카운트해두면 8-1의
  가설 2·3(클릭이 요청을 못 만듦)과 가설 1·4(요청은 나갔지만 응답이 이상함)를 로그만 보고 즉시
  갈라낼 수 있다.
- **`comment_count`가 페이지네이션 도중 바뀌는지 그 자체를 신호로 남기기.** 가설 1을 검증하려고
  또 재기동할 필요 없이, `이전 댓글` 페이지를 받을 때마다 `data.total`(또는 응답에 실린 총 댓글 수)을
  로그에 남기도록 해두면, 다음 실기동 한 번으로 "페이지네이션 중 목록이 실제로 변했는가"를 바로
  확인할 수 있다.
- **밴드 프론트엔드의 콘솔 에러도 같이 수집.** CDP `Runtime`/`Log` 도메인으로 페이지 콘솔 에러를
  같이 캡처해두면, 우리 합성 클릭이 밴드 쪽 내부 상태 머신을 깨뜨리고 있는지(예: 너무 빠른 연속
  네비게이션) 사람이 화면을 보지 않아도 알 수 있다.
- 요약하면: 오늘은 "질문 하나당 재기동 한 번"이었는데, 다음엔 **"재기동 한 번으로 질문 여러 개에
  답할 수 있는 로그"를 먼저 깔아두고 실기동하는 순서**로 바꾸면 재기동 횟수(§4의 anti-abuse 우려)와
  세션 소요 시간을 둘 다 줄일 수 있다.

## 9. 다음 세션 시작 지점 (2026-07-17 예정)

1. 위 8-2의 트레이스 로깅(요청 생명주기 + 페이지네이션 중 total 변화 + 콘솔 에러)을 코드에 먼저
   넣는다 — 실기동 전에. **→ §10에서 완료함(실기동 전).**
2. 그 상태로 한 번만 실기동해서 8-1의 가설 1~3을 동시에 검증한다(재기동 최소화).
3. `postsCommentsComplete`가 47/47(교수님 과제글 제외 전량)이 될 때까지, 원인이 코드 버그면
   고치고 타이밍/서버 쪽 문제면 수집 스케줄 조정을 사용자와 상의한다.
4. 여기까지 되면 M1 acquire 단계는 사실상 마무리 — 그다음은 scoring(채점) 스크립트로 넘어갈 차례.

## 10. 네 번째 세션(2026-07-17) — 트레이스 로깅 계측 추가 (실기동 전)

§8-2 계획대로, 실기동을 하지 않고 코드에 계측만 먼저 넣었다(재기동 0회). 다음에 실기동할 때
`BSC_TRACE=1`로 켜면 §8-1의 가설 1~3(순회 중 실시간 댓글 유입 / 세션 첫 요청 콜드스타트 /
페이싱 축소 부작용)을 재기동 한 번으로 동시에 검증할 수 있는 로그가 쌓인다.

### 10-1. 추가된 것

- `acquire/capture/tracer.js`(신규): `BSC_TRACE=1`일 때만 활성화되는 ndjson 로거.
  `logs/trace/trace_<bandId>_<시각>.ndjson`에 한 줄씩 이벤트를 남긴다. 꺼져 있으면
  `record()`가 완전 no-op이라 평소 실행엔 영향 없음.
- `acquire/capture/cdp-capture.js`: `Network.requestWillBeSent`/`Network.loadingFailed`를
  새로 구독해 **data-host 요청이 애초에 발생했는지**를 `phase:'request-sent'`/
  `'request-failed'`로 기록. 기존 `Fetch.requestPaused` 처리부에서 `params.networkId`로
  같은 요청을 짝지어 `phase:'response-received'`(응답 도착까지 걸린 시간 `durationMs`
  포함) 또는 `phase:'response-body-error'`를 기록. 이제 "요청이 안 나감"과 "요청은 나갔는데
  응답/바디 처리가 실패함"을 로그만으로 구분할 수 있다(§8-2 두 번째 항목 해결).
  `BSC_TRACE=1`일 때만 추가로 `Log.enable`/`Runtime.enable`을 켜서 밴드 페이지의 콘솔
  에러·예외(`Log.entryAdded`, `Runtime.exceptionThrown`, `Runtime.consoleAPICalled`)도
  `phase:'console-error'`로 같이 남긴다.
- `acquire/capture/interceptor.js`: `handleCommentList`에서 매 페이지마다
  `phase:'commentPage'`로 `postNo`/`contentType`/`total`/`count`/`previousParams`를 기록.
  같은 `postNo`에 대해 여러 줄의 `total` 값을 비교하면 순회 도중 실제로 댓글 수가 늘었는지
  (§8-1 가설 1) 바로 확인된다.
- `acquire/main.js`: 밴드마다 `tracer`를 새로 만들어 `interceptor`/`attachCdpCapture`에
  전달하고, 밴드 종료 시(`finally`) `tracer.close()`.
- `node --check`로 수정/신규 파일 전부 문법 확인 완료. **아직 실기동 검증 전.**

### 10-2. 다음 세션(실기동)이 할 일

1. `BSC_TRACE=1 npx electron .`로 1회만 실행(세션 persist라 재로그인 불필요할 가능성 높음).
2. 수집이 끝나면(또는 문제의 post_no=48/4 구간을 지난 뒤) `logs/trace/trace_<bandId>_*.ndjson`을
   열어:
   - `postNo`가 48 또는 4인 `phase:'commentPage'` 줄들을 시간순으로 보고 `total` 값이
     바뀌는지 확인 → 바뀌면 가설 1(실시간 댓글 유입) 확정, 코드가 아니라 수집 타이밍을
     조정하는 쪽으로 사용자와 상의.
   - 같은 두 post_no에 대해 `phase:'request-sent'`는 있는데 `'response-received'`/
     `'response-body-error'`가 없는 구간이 있는지 확인 → 있으면 요청 자체가 씹힌 것이니
     가설 2(콜드스타트)나 3(페이싱 축소 부작용) 쪽에 더 무게가 실림. `durationMs`가
     유독 크게 튀는 첫 요청이 있는지도 같이 본다.
   - `phase:'console-error'` 줄이 댓글 수집 구간에 몰려있는지 확인 → 있으면 우리 클릭이
     밴드 내부 상태 머신을 깨뜨리고 있다는 직접 증거.
3. 위 분석으로 원인이 갈리면: (a) 실시간 유입이면 §8-1처럼 수집 스케줄 조정을 사용자와
   상의, (b) 코드 버그(클릭 타이밍 등)면 그 자리에서 고치고 같은 트레이스로 재확인(추가
   재기동 최소화 — 가능하면 이미 쌓인 로그로 끝낼 것), (c) 세션 피로/서버 스로틀링이면
   재기동 자체를 하루 이상 쉬었다가 재시도.
4. `postsCommentsComplete`가 47/47이 되면(또는 원인이 "코드 문제 아님"으로 확정되면) M1
   acquire 단계 종료 — scoring 스크립트로 넘어갈 차례.

## 11. 🚨 다섯 번째 세션(2026-07-17) — 로그인 자체가 막힘. 댓글 문제보다 상위의 새 증상

`BSC_TRACE=1 BSC_DEBUG_UNCLASSIFIED=1`로 딱 한 번만 실기동했다(계획대로 재기동 없이 계측만
먼저 넣고 실행). 그런데 **댓글 페이지네이션까지 가지도 못했다** — 이전 세션들과 달리 이번엔:

- 창에 로그인 폼이 아니라 **네이버의 일반 오류 페이지**("잠시 후 다시 시도해 주세요" +
  블로그/공지사항/도움말 링크만 있는 화면, 스크린샷으로 사용자가 직접 확인)가 떴다.
- 그대로 무한로딩 상태로 멈춤(사용자 직접 확인).
- 트레이스 로그(`logs/trace/trace_103239777_*.ndjson`)에는 **딱 2줄**만 찍혔다:
  1. `phase:"console-error", source:"exception", text:"Uncaught", url:"https://auth.band.us/s/login/getKey?..."` —
     로그인 키를 받아오는 JSONP 콜백(`getKey`) 요청에서 처리되지 않은 예외가 터짐.
  2. Electron의 기본 CSP 보안 경고(무관한 노이즈).
- `authOk`/`request-sent` 등 data-host 관련 이벤트는 **단 하나도** 없었다 — 즉 우리 캡처
  코드까지 도달하기 전, **band.us/네이버 인증 단계 자체**에서 막혔다.

### 11-1. 해석

이건 지금까지 쫓던 "댓글 페이지네이션 멈춤"(§7-1, §8-1)과는 **다른 계층의 문제**다. 여지껏
문제는 로그인 이후 댓글 API 단계였는데, 이번엔 로그인 화면조차 정상적으로 못 띄웠다.
`auth.band.us`의 JSONP 콜백이 예외를 던지고 네이버가 일반적인 "다시 시도해 주세요"류 오류
페이지를 돌려주는 패턴은, 네이버/밴드 쪽에서 **이 세션(혹은 이 IP)에 대해 짧은 시간 반복
접속을 이상 트래픽으로 보고 일시적으로 차단·스로틀링**하고 있을 가능성이 가장 유력하다 —
§8-1의 가설 4("세션 누적 피로/속도 제한")가 예상보다 훨씬 이른 단계(로그인)에서, 예상보다
빨리 현실화된 것으로 보인다. 이틀에 걸쳐 20회 넘게 재기동한 누적이 트리거했을 개연성이 높다.

**중요한 정정(사용자가 직접 지적)**: 이전 세션들에서 AI가 "세션이 persist돼 있으니 로그인은
스킵될 것"이라고 여러 번 말했지만, **실제로는 매번 예외 없이 사람이 직접 로그인해야 했다**.
즉 "재기동해도 로그인 절차가 필요 없다"는 가정 자체가 틀렸었다 — 다음부터는 이 가정을 다시
꺼내지 말 것(자세한 내용은 `MEMORY.md`의 관련 피드백 메모리 참고).

### 11-2. 다음 세션이 할 일 (실기동 금지 — 사람이 먼저 판단해야 함)

1. **오늘은 더 재기동하지 말 것.** 막혀 있는 상태에서 계속 재시도하면 차단이 더 굳어지거나
   계정 자체가 잠길 위험이 있다(브리프 §0의 "자동 로그인 구현 금지 — 계정 잠금 위험" 조항과
   같은 맥락의 리스크).
2. 사용자가 **평범한 일반 브라우저**(이 앱의 persist 세션이 아닌 곳)로 band.us에 정상
   로그인되는지 직접 확인해야 한다 — 되면 "이 Electron 세션/IP만 일시적으로 걸린 것"이고,
   그것도 안 되면 "계정 자체가 잠긴 것"이라 대응이 완전히 달라진다.
3. 최소 몇 시간(가능하면 하루) 쉬었다가 재시도. 재시도할 때도 §4/§8-2 원칙대로 한 번에
   끝내려 하지 말고, 이번처럼 로그인 단계에서 또 막히는지부터 조용히 확인한 뒤 다음 단계로
   넘어갈 것.
4. 로그인이 정상적으로 다시 되면, 그제서야 §10의 트레이스 계측으로 §7-1/§8-1의 원래 댓글
   페이지네이션 문제로 돌아간다 — 이번 세션은 그 문제에 대해 **아무 데이터도 못 얻었다**.

## 12. 같은 세션 재시도(2026-07-17) — 사용자가 밴드 접속정보 초기화 후 로그인 성공,
##    §7-1/§8-1 문제의 실제 원인을 트레이스로 특정함

§11 직후 사용자가 "밴드 접속정보를 모두 초기화"하고 재시도를 요청했다. 창을 완전히 종료
(`Stop-Process`로 잔여 electron 프로세스까지 확인 후 강제 종료 — 백그라운드 bash 태스크만
죽이는 걸로는 electron 자식 프로세스가 안 죽는 걸 확인함, 다음에도 주의)하고 `BSC_TRACE=1
BSC_DEBUG_UNCLASSIFIED=1`로 다시 실행했다. **이번엔 로그인 화면이 정상적으로 떴고(§11의
차단이 세션/캐시 문제였을 가능성 — 계정 자체 잠김은 아니었던 것으로 보임), 사용자가 로그인 후
전체 순회가 끝까지 완주했다.** 재기동 1회로 끝남(오늘 두 번째이자 마지막 재기동).

### 12-1. 최종 상태

```
{"feedExhausted":false,"totalPosts":48,"postsInRange":48,"postsNeedingComments":46,
 "postsCommentsAttempted":46,"postsCommentsComplete":38,"postsRepliesIncomplete":[],
 "memberCount":57}
```
8개 글 미완료(post_no 48,43,33,32,31,23,16,4) — §7-1 때(39/47, 경고 2건)와 규모는 비슷하지만,
이번엔 **부분-실패 경고 로그 버그(§7 항목)가 이미 고쳐져 있어서 8건 전부가 경고로 잡혔다** —
"조용히 새는" 결손은 이제 없다.

### 12-2. 트레이스로 확정한 것 — §8-1의 가설 1~4는 전부 기각. 원인은 두 개의 서로 다른 코드 버그

`logs/trace/trace_103239777_1784216496906.ndjson`(955줄)를 `postNo`별로 `request-sent`/
`response-received`/`commentPage` 이벤트 수를 세어 분석한 결과:

- **댓글이 20개를 넘는(=2페이지 이상 필요한) 글은 정확히 8개였다: 47, 45, 43, 33, 32, 31, 23,
  16.** 이 중 **47과 45만 실제로 2번째 페이지 요청이 나갔다**(각각 `get_comments` 요청이
  3회 — preflight까지 포함해 request-sent 6줄). **나머지 6개(43·33·32·31·23·16)는 첫
  페이지(정확히 20개, `previousParams`에 실제 다음 페이지 파라미터가 있음) 이후 `get_comments`
  요청이 단 한 번도 더 나가지 않았다**(request-sent가 딱 2줄 = preflight+최초 1회뿐). 즉
  **"이전 댓글 더보기" 클릭(`clickLoadMoreComments`)이 6/8 = 75%의 경우 후속 API 요청 자체를
  못 만들었다** — 응답이 느리거나 실패한 게 아니라 **요청이 애초에 안 나갔다**. 이건 §8-1이
  세웠던 가설 1(실시간 댓글 유입으로 커서 무효화)·2(콜드스타트)·3(페이싱 축소)·4(서버
  스로틀링) 그 어느 것도 아니다 — **네트워크/서버 문제가 아니라 우리 쪽 클릭 자동화가 대부분의
  경우 다음 페이지 로드를 트리거하지 못하는 UI 자동화 버그**다.
- **post_no=48과 4는 완전히 다른 증상이다.** 둘 다 댓글 총량이 20개 이하라 애초에 페이지네이션이
  필요 없었고(48: count=17/total=17, 4: count=11/total=14, 둘 다 `previousParams:null`로 첫
  페이지에 이미 완결), 인터셉터는 두 글 다 **정상적으로 딱 1건의 완결된 commentPage를
  캡처했다**(트레이스에 남아있음, request-sent도 정확히 1회 왕복분만 있고 실패 흔적 없음). 그런데
  `collector.js`의 재시도 루프는 이 이벤트를 한 번도 못 받고 "확보=0건"으로 3회 재시도 후
  포기했다 — **인터셉터는 이벤트를 emit했는데 collector의 `waitForEvent`/`takeRecent`가 그걸
  못 찾은, 우리 쪽 이벤트 버스 소비 로직의 버그**로 보인다. post_no=48은 순회의 첫 글(콜드스타트
  가설과 겹침)이지만 post_no=4는 첫 글이 아니므로 "그냥 첫 시도라서"만으로는 설명 안 된다 —
  구조적인 소비 버그일 가능성이 크다.
- **부수적으로 확인된 것**: 댓글 응답의 `total` 필드는 실제 페이지네이션 완결 여부(`previousParams
  === null`)와 자주 어긋난다(예: post_no=30은 `count=17`인데 `total=30`이면서도 첫 페이지에서
  바로 `previousParams:null`로 "완결" 처리됨 — 정상 케이스에서도 반복 관찰됨). **`total`은
  신뢰할 수 있는 완결 신호가 아니다**(아마 삭제/숨김 댓글까지 포함하는 값으로 추정) —
  `collector.js`가 이미 `total`이 아니라 `previousParams`만으로 완결을 판단하고 있는 건
  다행히 맞는 설계였다. 지난 세션(§8-1 가설 1)이 `total`의 세션별 변화(11→14→16)를 "실시간
  댓글 유입"의 증거로 해석했었는데, 이번 관찰을 보면 그 변화가 실제 유입이 아니라 `total` 필드
  자체의 잡음(비페이지네이션 카운트 방식)이었을 가능성도 배제 못 한다 — 재확인 불필요, 그냥
  `total`을 신뢰 지표로 쓰지 않으면 그만이다.
- 콘솔 에러는 Electron 기본 CSP 경고 6건뿐이었다(밴드 자체 JS 예외는 없음) — 우리 클릭이
  밴드 내부 상태 머신을 깨뜨리는 것도 아니다.

### 12-3. 다음 세션이 할 일 (이제 가설이 아니라 정확한 버그 2개를 고치면 됨)

1. **버그 B(더 큰 영향, 6/8): `clickLoadMoreComments`가 다음 페이지 요청을 못 만듦.**
   지금은 클릭 성공 여부(버튼을 찾았는지, 실제로 클릭했는지, 스크롤 폴백으로 빠졌는지)를 전혀
   기록하지 않는다 — 이게 다음으로 넣어야 할 계측이다. `acquire/collector.js`의
   `clickLoadMoreComments`가 텍스트 매칭으로 찾은 버튼의 `outerHTML`/`textContent`나 "버튼
   없음(스크롤 폴백)" 여부를 `postNo`와 함께 트레이스에 남기도록 고치고, 실패한 6개 글과
   성공한 2개 글(47/45) 사이에 어떤 차이가 있는지(버튼이 아예 안 잡혔는지, 잡혔는데 클릭이
   무반응이었는지) 다음 실기동 한 번으로 확인한다.
2. **버그 A(작은 영향, 2/8): 완결된 단일 페이지 commentPage 이벤트를 collector가 놓침.**
   `interceptor.js`의 `recent` 버퍼(`RECENT_LIMIT=200`, 전체 이벤트 타입 공유)나
   `collector.js`의 `waitForEvent`/`takeRecent` 소비 순서를 다시 점검해야 한다. 의심 지점:
   `collectCommentsInOpenModal` 호출 시점(`postDetail` 수신 후 `randomDelay`를 거친 뒤)과
   실제 `commentPage` emit 시점의 순서 — 모달을 열면 밴드가 `get_post`와 `get_comments`를
   거의 동시에 쏘는데, 후자가 먼저 도착해 버퍼에 들어가더라도 `takeRecent`가 못 찾는 이유를
   좁히려면 버퍼 조회 시점에 버퍼 크기/가장 오래된-최신 엔트리 타임스탬프를 같이 로그로
   남기는 게 다음 단서가 될 것.
3. 위 두 버그를 고친 뒤 재실기동 한 번으로 `postsCommentsComplete: 46/46`(교수 과제글 제외
   전량) 도달을 확인한다.
4. 되면 M1 acquire 종료 — scoring 스크립트로 이동.

## 13. 같은 세션, 계측 추가 후 두 번째 재실기동(2026-07-17) — 버그 A 근본 원인 특정 및 수정 완료

§12-3에서 예고한 대로 클릭 결과 트레이스(`clickLoadMore`/`clickNextPost`/
`openFirstVisiblePostModal`)와 이벤트 소비 경로 트레이스(`emit`/`takeRecent`/
`waitForEvent-resolved`)를 `interceptor.js`/`collector.js`에 추가하고(코드는 아래 §13-3 참고),
`BSC_TRACE=1 BSC_DEBUG_UNCLASSIFIED=1`로 오늘 세 번째 재실기동했다(로그인 정상, 전체 완주:
`postsCommentsComplete: 39/47`, 미완료 post_no 48·45·33·32·31·23·16·4 — §12의 43 대신 45가
실패한 것만 다름, 나머지는 동일 패턴 → **어느 글이 실패하는지 자체가 실행마다 조금씩 바뀐다는
것도 "고정된 특정 글의 문제"가 아니라 타이밍에 좌우되는 레이스라는 방증**).

### 13-1. 버그 A(post_no=48/4류) 근본 원인 확정 — collector.js의 이중 소비 경로 미동기화

트레이스를 시간순으로 정밀 재구성한 결과(`logs/trace/trace_103239777_1784218214885.ndjson`),
post_no=48이 **두 번 처리되고 있었다**:

1. `walkPostsViaModal`이 post 48을 열고 `pendingDetail`(label `postDetail:open-first`)이
   **라이브 리스너 경로**로 resolve됨(버퍼에 아직 없었음 — 첫 글이라 당연함).
2. `collectCommentsInOpenModal`이 post 48의 댓글(18건, 완결)을 **버퍼 경로**로 정상 소비함
   (`takeRecent` matched=true, latency 0). `previousParams===null`이라 `topLevelDone=true`로
   즉시 성공 종료 — **여기까지는 완전히 정상**.
3. 곧바로 `walkPostsViaModal`이 "다음 글" 대비용 `pendingDetail = waitForEvent(...,
   'postDetail:after=48')`을 등록하는데, 이 predicate는 **`bandId`만 확인하고 post_no는
   전혀 안 본다**. 그런데 이 호출이 **실제 클릭(`clickNextPost`)이 일어나기도 전에, 등록하자마자
   버퍼에서 뭔가를 즉시 매치해버렸다**(latency 0, 아직 "다음 글" 요청조차 안 나간 시점).
4. 매치된 건 다름아닌 **1번에서 라이브 리스너로 이미 처리했던 바로 그 post 48의 `postDetail`
   이벤트**였다. **원인**: `interceptor.js`의 `emit()`은 같은 이벤트를 (a) `bus.emit()`으로
   라이브 리스너에게, (b) `recent` 배열에 push해서 나중에 오는 `takeRecent()` 호출자에게 —
   **두 개의 독립된 경로로 동시에** 흘려보낸다. 라이브 리스너가 이벤트를 받아가도 `recent`
   배열 쪽 항목은 `consumed:false`로 그대로 남는다(오직 `takeRecent()`만 `consumed=true`로
   표시함). 그래서 **라이브 리스너로 이미 다 쓴 이벤트가 `recent` 버퍼엔 "아직 안 쓴 것"으로
   남아있다가, 나중에 predicate가 느슨한(post_no를 안 보는) 다른 `takeRecent()` 호출에
   재활용**돼버린 것.
5. 결과: `walkPostsViaModal`이 **post 48을 "다음 글"이라고 착각하고 두 번째로 처리**한다.
   `post.post_no`가 여전히 48이므로 `posts[]`에 48이 중복으로 쌓이고, `collectCommentsInOpenModal`이
   또 호출된다. 이번엔 진짜 댓글 이벤트가 이미(2번에서) 소비돼 버렸으므로 3번의 attempt 모두
   `waitForEvent`가 **timeout**으로 끝난다 — 이게 로그에 찍힌 "post_no=48: 3회 재시도 후에도
   못 받음(확보=0건)"의 진짜 정체다. **댓글이 유실된 게 아니라, 이미 다 받은 글을 한 번 더
   기다리다가 못 받은 것**이었다.

post_no=48이 유독 잘 걸리는 이유: 이 레이스는 "postDetail이 **라이브 리스너 경로**로
resolve된 직후에만" 발생한다(버퍼 경로로 resolve되면애초에 라이브 리스너가 안 걸리므로
이 이중 경로 문제 자체가 없다). post_no=48은 순회의 **첫 글**이라 등록 시점에 버퍼가
비어있어 항상 라이브 리스너 경로를 타므로, 이 레이스에 거의 매번 걸린다. 다른 글들은
밴드가 인접 글을 미리 fetch해두는 경향 때문에 버퍼 경로로 resolve되는 일이 많아 레이스가
드물게만 발생한다 — post_no=4(1차 재실기동)처럼 가끔 다른 글에서도 튀는 이유.

### 13-2. 버그 A 수정 완료

`acquire/collector.js`의 `waitForEvent`에서, 라이브 리스너(`handler`)가 이벤트를 매치해
소비하는 바로 그 순간 **같은 payload 객체를 참조 동일성(`p === payload`)으로 `recent`
버퍼에서도 소비 처리**하도록 한 줄 추가했다:

```js
if (interceptor.takeRecent) {
  interceptor.takeRecent(eventName, (p) => p === payload, `${label || eventName}:reconcile-buffer`);
}
```

`interceptor.js`의 `emit()`이 `bus.emit`과 `recent.push` 양쪽에 **같은 객체 참조**를 넘기므로
(별도 clone 없음) 이 참조 동일성 체크는 항상 정확히 그 항목 하나만 잡는다 — 다른 항목을
잘못 지울 위험 없음. `node --check` 통과. **아직 실기동으로 재확인 전** — 다음 세션(또는
오늘 한 번 더 돌린다면) 이 수정으로 post_no=48류 실패가 사라지는지 확인이 필요하다.

### 13-3. 버그 B(다수 페이지 있는 글의 "더보기" 클릭 무반응) — 근본 원인은 아직 미확정, 증거만 강화됨

post_no=45(2차 재실기동에서 실패)의 클릭 결과 트레이스:

```
attempt=0(reason=need-next-page): clicked=true, candidateCount=312, matchCount=1, text="이전 댓글", visible=true
attempt=1(reason=no-page-received): clicked=false, candidateCount=400, matchCount=0
attempt=2(reason=no-page-received): clicked=false, candidateCount=400, matchCount=0
```

**버튼을 정확히 찾아서(matchCount=1, 텍스트="이전 댓글", 화면에 보임) 클릭까지 했는데, 이후
`get_comments` 요청이 단 한 번도 안 나갔다**(해당 post_no의 emit이 전체 트레이스에 딱 1건 —
최초 페이지뿐). 클릭 직후 후보 엘리먼트 수가 312→400으로 늘어난 것으로 보아 **클릭이 DOM에
뭔가 변화는 일으켰다**(로딩 스피너, 상태 배지 등 추정) — 하지만 그게 실제 다음 페이지
요청으로 이어지지는 않았고, 이후 재시도에서는 "이전 댓글" 텍스트에 매치되는 엘리먼트 자체가
사라졌다(matchCount=0). 즉 **band.us 프론트엔드가 클릭을 받고도 요청을 안 보내거나, 우리
`target.click()`(synthetic click)이 band의 실제 핸들러가 기대하는 이벤트가 아니라서 무시된
것**으로 추정된다 — `clickNextPost`(글 넘기기 버튼)는 같은 `.click()` 방식으로 거의 항상
성공하므로, "synthetic click 자체가 이 사이트에서 전반적으로 안 먹힌다"는 아니고 **이
특정 버튼(또는 그 리액트 핸들러의 바인딩 방식)에 한정된 문제**로 보인다.

다음에 시도해볼 것(우선순위순):
1. `target.click()` 대신 `MouseEvent('mousedown')`→`MouseEvent('mouseup')`→`click`을 좌표
   포함해서 순서대로 `dispatchEvent`하는 방식으로 바꿔보기 (일부 React 컴포넌트는 합성
   `click()`이 아니라 실제 포인터 이벤트 시퀀스를 기대함).
2. 클릭 후 곧바로 `randomDelay`로 넘어가지 말고, 클릭 직후 스코프 안 DOM이 실제로 "로딩 중"
   같은 과도기 상태로 바뀌는지 잠깐(예: 300ms) 지켜보고 그 상태가 다시 안정되는 시점까지
   기다려본 뒤에도 요청이 안 나가는지 확인 — 지금은 클릭 즉시 `randomDelay` 후 바로 다음
   attempt로 넘어가므로, 혹시 band 쪽이 클릭을 받고도 렌더링 락 때문에 요청을 지연시키는
   경우를 놓치고 있을 수 있음.
3. 실패 재현 시 `clickLoadMore` 트레이스의 `candidateCount`/`matchCount` 변화를 계속 남겨서,
   "버튼이 사라짐"(matchCount:0)이 매번 재현되는지 아니면 가끔은 버튼이 그대로 남아있는데도
   요청만 안 나가는 경우가 있는지 구분 — 전자면 band 자체 상태 전이 문제, 후자면 우리 클릭이
   핸들러에 안 먹힌 문제 쪽에 무게가 실림.

### 13-4. §13-3의 개선안 1번(포인터 이벤트 시퀀스)도 같은 세션에 바로 적용함

재기동 횟수를 아끼려고, 검증 전이지만 §13-3 1번 제안(pointerdown→mousedown→pointerup→
mouseup→click을 좌표 포함해서 순서대로 dispatch)을 `clickLoadMoreComments`에 바로 적용해뒀다
(`target.click()` 한 줄 대신). **버그 A 수정과 마찬가지로 아직 실기동 검증 전** — 다음
재기동 한 번으로 버그 A/B 수정 둘 다 동시에 확인 가능하다. 효과가 없으면(버그 B 재현율이
그대로면) 이 변경은 되돌리고 §13-3의 2·3번(클릭 후 DOM 안정화 대기, candidateCount 변화
재확인)으로 넘어갈 것.

### 13-6. 같은 세션, 네 번째 재실기동(2026-07-17) — 수정 검증 결과: 버그 A 확정 해결, 버그 B는 클릭 방식 문제가 아님

`postsCommentsComplete: 42/47`(직전 39/47에서 개선). 실패 5건: post_no 45·43·33·23·16 —
**전부 "확보=20건"류(페이지네이션 필요 케이스)뿐, "확보=0건"류는 단 하나도 없었다.**

- **버그 A: 확정 해결.** `reconcile-buffer` 라벨의 `takeRecent` 호출이 이번 실행에서 6번
  발생했고 전부 `matched:true`였다 — 라이브 리스너가 이벤트를 받을 때마다 버퍼 쪽 동일
  객체도 정확히 소비 처리됐다는 뜻. 그 결과 post_no=48류(첫 글이라 항상 라이브 리스너
  경로를 타던 케이스)의 이중 처리가 이번엔 한 건도 재현되지 않았다. §13-1/§13-2의 진단과
  수정이 실기동으로 확인됐다 — **더 손댈 필요 없음.**
- **버그 B: §13-3의 개선안 1번(포인터 이벤트 시퀀스) 효과 없음 — 가설 기각, 코드 되돌림.**
  실패한 5건 중 post_no=33은 `clickLoadMore`가 정확히 버튼을 찾아 전체 포인터 시퀀스
  (pointerdown→mousedown→pointerup→mouseup→click)를 쐈는데도(`clicked:true, matchCount:1`)
  후속 `get_comments` 요청이 여전히 안 나갔다(`emit` 1건뿐). **synthetic click의 이벤트
  종류(단순 `.click()` vs 풀 포인터 시퀀스)는 원인이 아니라는 게 실측으로 확정됐다** —
  `acquire/collector.js`의 `clickLoadMoreComments`를 `.click()`로 되돌렸다(불필요한 복잡도
  제거, `node --check` 통과).
- **새로 관찰된 패턴**: 이번 실행에서는 실패 5건 중 4건(45·43·23·16)이 **`attempt=0`부터
  이미 `matchCount:0`**(버튼을 아예 못 찾음)이었다 — 직전 실행에서 post_no=45가 `attempt=0`엔
  버튼을 찾아 클릭했지만 `attempt=1`부터 못 찾았던 것과 다른 패턴이다. 즉 **"버튼을 못
  찾는 시점"조차 매 실행마다 달라진다** — 같은 글, 같은 코드인데 어떤 실행에선 첫 시도부터
  못 찾고 어떤 실행에선 첫 시도는 성공한다. 이는 DOM 자체가 매 실행 도착 타이밍에 따라
  다른 상태에 있다는 뜻이라, **고정된 selector 문제가 아니라 순수 타이밍/레이스 문제**라는
  기존 결론(§12-2)을 다시 한번 뒷받침한다.
- 성공 사례(post_no=47, 32 등)는 `attempt=0`에서 버튼을 찾아 클릭하면 대체로 이어졌다 —
  실패군은 그 첫 클릭 자체가 이미 어긋나 있는 경우가 많아졌다. §13-3의 남은 개선안(클릭
  후 DOM 안정화를 기다렸다가 재확인)이 다음으로 시도해볼 만한 방향으로 남는다.

### 13-7. 다음 세션이 할 일

1. 버그 A는 끝났다 — 재확인 불필요.
2. 버그 B는 §13-8에서 클릭 타이밍(사전 지연) 가설도 기각됨 — 남은 후보는 §13-8 참고.
3. 버그 B가 해결되면 `postsCommentsComplete`가 교수 과제글 제외 전량에 도달할 것 — 되면 M1
   acquire 종료, scoring 스크립트로 이동.
4. 추가 실기동 전에 사용자와 계속 여부를 확인할 것(§4 원칙).

## 14. 같은 세션, 다섯 번째 재실기동(2026-07-17) — 클릭 지연 가설도 기각. 트레이서 크래시 버그 발견·수정

`clickLoadMoreComments` 호출 직전에 700ms 고정 지연(`PRE_CLICK_SETTLE_MS`)을 넣고 재실기동했다.

### 14-1. 결과: 클릭 타이밍도 원인이 아님 — 오히려 실패 패턴이 처음으로 "고정"됨

`postsCommentsComplete: 42/47`, 실패 5건: **post_no 45·43·33·23·16 — 직전(4차, 지연 없음)
실행과 완전히 동일한 집합이다.** 지금까지는 실행마다 실패하는 글이 달라졌는데(1차: 48·43·33·32·31·23·16·4,
2차: 48·45·33·32·31·23·16·4, 4차: 45·43·33·23·16), **4차와 5차가 처음으로 정확히 일치했다.**
700ms 지연을 넣었는데도 실패 집합이 한 글자도 안 바뀌었다는 건 "클릭이 너무 이르다"는 가설도
기각됐다는 뜻이다.

`total`(서버가 보고하는 댓글 총량) 비교:
- 실패 5건: 29, 28, 51, 41, 52
- 성공한 다중페이지 글(47·32·31): 46, 32, 22

`total`만으로는 깔끔하게 안 갈린다(성공한 47이 실패한 33·23·16보다 total이 크거나 비슷함) —
**단순히 "댓글이 많은 글이라 실패한다"도 아니다.** 다만 4·5차가 정확히 같은 집합으로
실패했다는 건 이게 완전히 무작위(pure random race)는 아니고, **이 특정 글들에 뭔가 재현
가능한 공통점이 있을 가능성**을 시사한다 — 다음 세션이 우선 조사할 지점.

### 14-2. 수집은 완주했으나 정리 단계에서 트레이서가 앱 전체를 크래시시킴 — 수정 완료

수집 자체(`모든 밴드 수집 완료` 로그까지)는 정상 종료됐지만, 그 직후 Electron이
`Uncaught Exception: Error [ERR_STREAM_WRITE_AFTER_END]: write after end`로 죽었다
(스크린샷으로 사용자가 직접 확인 — `acquire/capture/tracer.js:18` → `Object.record` →
`acquire/capture/cdp-capture.js:166`의 `Debugger.onMessage`).

**원인**: `main.js`가 밴드 처리를 끝내며 `cdp.detach()`(메시지 리스너 제거) 후 바로
`tracer.close()`(스트림 `.end()`)를 호출하는데, CDP의 `Debugger.onMessage` 핸들러는
`async`라서 `cdp.detach()` 시점에 **이미 실행 중이던(아직 `await`에 걸려있던) 핸들러
호출은 리스너 제거와 무관하게 계속 진행**된다. 그 핸들러가 나중에 `trace.record(...)`를
부르면, 이미 `.end()`된 스트림에 `write()`를 시도해 Node가 예외를 던지고 — 이게 Electron
메인 프로세스의 uncaught exception이 되어 앱 전체가 죽는다.

**수정**(`acquire/capture/tracer.js`): `close()`가 불리면 내부 `closed` 플래그를 세우고,
`record()`는 그 플래그가 서면 그냥 조용히 무시하도록 고쳤다 — 비동기 핸들러의 정확한 종료
시점을 보장하려 하기보다(어려움), "정리 이후의 기록 시도는 안전하게 버린다"는 더 단순하고
확실한 방향으로 고쳤다. `node --check` 통과. **이 크래시는 트레이서(오늘 추가한 진단 코드)
자체의 버그이지 원래 앱 로직과는 무관함** — 수집이 완주된 뒤에만 터지므로 지금까지의
`postsCommentsComplete` 수치들은 전부 유효하다.

### 14-3. 다음 세션이 할 일

1. §14-2의 트레이서 크래시 수정을 재실기동으로 확인(다른 계측과 같이 검증 가능).
2. 버그 B: §14-1에서 실패 집합이 4·5차에 걸쳐 고정된 것을 실마리로, 이 5개 글(45·43·33·23·16)에
   진짜 공통점이 있는지 조사 — 예: 작성자가 같은지, 댓글 작성 시각 패턴, 첨부파일/이미지
   유무, 또는 `clickLoadMoreComments`의 스코프 탐색이 이 글들에서만 다르게 동작하는지
   (`candidateCount` 절대값이나 변화 패턴을 다시 비교). §13-3의 남은 개선안(클릭 후 DOM이
   실제로 안정되는지 지켜보기)도 여전히 유효한 다음 시도.
3. 오늘 재기동 5회 + 크래시 1회 — 다음 실기동 전 사용자와 계속 여부 확인.

## 15. 같은 세션, 여섯 번째 재실기동(2026-07-17) — 실패가 100% 재현됨 + 버튼이 스코프에 아예 없다는 것 확정

오프라인 분석(작성자·사진·본문길이·댓글수 비교)으로는 실패 5건(45·43·33·23·16)과 성공 글
사이에 깔끔한 구분선을 못 찾았다(예: 작성자 황인각·남동명·윤배희는 성공한 글에도 실패한
글에도 나옴). DOM 레벨 근거가 필요해 `clickLoadMoreComments`가 `matchCount:0`일 때 "댓글"이
들어간 다른 후보 텍스트까지 넓게 긁어오도록 계측을 추가하고(§14-3의 계획) 재실기동했다.

### 15-1. 실패가 세 번째로 완전히 동일하게 재현됨

`postsCommentsComplete: 42/47`, 실패 정확히 45·43·33·23·16 — **4차·5차·6차 실행 3연속으로
정확히 같은 5개 글에서 실패했다.** 클릭 지연(§13-7)도, 클릭 방식(§13-6)도 안 바뀐 상태에서
3연속 동일 — 이제 "타이밍 레이스"보다 "이 5개 글에 고정된 구조적 원인이 있다" 쪽이 훨씬
유력해졌다.

### 15-2. 핵심 발견: 실패한 글에서는 "이전 댓글" 버튼이 스코프 안에 아예 존재하지 않는다

`matchCount:0`이었던 4건(45·43·23·16, attempt 0부터) 전부 `broadCommentTexts`가 **완전히
동일**했다:
```
["댓글쓰기","댓글","댓글 수정","이 멤버의 댓글 차단하기","댓글 삭제",
 "댓글 수정","이 멤버의 댓글 차단하기","댓글 삭제"]
```
"댓글"이 들어간 요소를 스코프 전체에서 다 긁었는데도 **전부 댓글 관리 메뉴(수정/삭제/차단)뿐,
페이지네이션과 관련된 텍스트가 단 하나도 없다.** 즉 버튼이 숨겨져 있거나 문구가 바뀐 게
아니라 — **우리가 검색하는 스코프 안에 "더 보기" 트리거 자체가 존재하지 않는다.**

또 하나 중요한 관찰: **post_no=47(성공)은 클릭을 딱 한 번만 했는데 그 한 번으로 남은 페이지
전부(0건짜리 응답 + 14건짜리 응답, 두 개의 `get_comments`가 거의 동시에)를 받았다** — 즉
"클릭 1번 = 페이지 1장"이 아니라 **"클릭 1번 = 남은 전량을 한 번에 로드"**하는 방식일
가능성이 높다. 그렇다면 실패한 5건은 애초에 "두 번째 클릭이 실패한 것"이 아니라 **"그
한 번의 결정적인 클릭이 아예 안 됐거나, 됐어도 아무 반응이 없었던 것"**이고, 이후 재시도들이
`matchCount:0`인 이유는 **그 유일한 트리거가 뭔가의 이유로 이미 사라졌거나, 애초에 우리
스코프 계산이 그 트리거를 포함하지 못했기 때문**일 가능성이 있다.

### 15-3. 다음 가설: 모달 스코프 탐색(`.closest('[class*="ly" i]')`)이 너무 좁을 수 있다

`clickLoadMoreComments`/`clickNextPost`가 쓰는 스코프 계산:
```js
var scope = (closeBtn && closeBtn.parentElement
  ? closeBtn.parentElement.closest('[id*="ly" i], [class*="ly" i], [class*="layer" i]')
  : null) || document;
```
`.closest()`는 **가장 가까운** 조상 하나만 찾는다. 댓글이 많은 글(실패한 5건은 전부 comment_count
27~52로 상대적으로 많음)일수록 모달 내부 DOM이 깊어지거나 레이어가 중첩될 가능성이 있고,
그러면 `.closest()`가 실제 "더 보기" 트리거를 포함하는 상위 레이어가 아니라 **더 안쪽의,
트리거를 포함하지 않는 좁은 컨테이너**에서 멈춰버릴 수 있다. `scopeIsDocument`는 계속
`false`였으므로(=`document`로 폴백된 적 없음) 이 좁은-스코프 가설과 모순되지 않는다 —
오히려 "`.closest()`가 뭔가를 찾긴 찾았는데, 그게 틀린 조상이었다"는 쪽에 힘을 싣는다.

**성공한 글(예: post_no=47)의 `candidateCount`(306)와 실패한 글들(120~475, 편차가 큼)을
비교해도 크기만으로는 못 가른다** — 스코프가 "좁아서" 문제라면 후보 수가 항상 작아야
하는데 33번 글은 475개로 오히려 제일 크다. 그러니 "스코프가 무조건 좁다"보다는 **"스코프가
매번 다른, 예측 못 하는 조상으로 튄다"**는 쪽이 더 정확한 설명일 수 있다 — 댓글 목록 DOM에
`class`/`id`에 "ly"가 들어가는 요소가 여러 겹으로 중첩돼 있고, 그중 어느 걸 잡느냐가
글마다(아마 댓글 개수·구조에 따라 DOM 깊이가 달라지면서) 달라지는 것으로 추정된다.

### 15-4. 다음 세션이 시도해볼 것 (우선순위순)

1. **스코프를 `.closest()` 대신 더 안전하게 잡기.** 가장 확실한 방법은 스코프 좁히기 자체를
   버리고 `document` 전체에서 "이전 댓글" 텍스트를 찾는 것 — 원래 스코프를 좁힌 이유(§1의
   `SCROLL_SCRIPT` 주석 — document 전체에서 찾으면 모달 뒤 피드 컨테이너가 걸릴 수 있다는
   것)는 **스크롤 대상(scrollHeight) 탐색에만 해당하는 이유**였지, 텍스트 매칭 버튼 탐색에는
   적용 안 될 가능성이 높다. `clickLoadMoreComments`만 스코프를 `document`로 바꿔서(또는
   `.closest()` 대신 `closeBtn.parentElement`에서 여러 단계 상위까지 순차적으로 넓혀가며
   찾도록) 재시도해볼 것 — 가장 적은 변경으로 가장 근본적인 가설을 검증할 수 있음.
2. 그래도 안 되면, 클릭 대신 §7-1이 원래 관찰했던 "화면에 실제로 렌더링된 댓글은 스크롤로
   끝까지 보인다"는 사실(§2-1)을 활용해 — `SCROLL_SCRIPT`를 댓글 리스트 컨테이너를 겨냥해
   실제로 스크롤시키는 방식(클릭이 아니라 무한스크롤 트리거)으로 완전히 바꿔보는 것도 고려.
3. 이번 발견(§15-2, "클릭 1번=전량 로드"일 가능성)이 맞다면, 재시도 루프의 `maxNoProgress`나
   대기 로직을 "여러 페이지를 여러 번 클릭"이 아니라 "결정적 클릭 1번 성공 여부"에 맞게
   재설계하는 것도 고려할 만하다 — 지금 로직은 여전히 "페이지당 1클릭"을 가정하고 있음.
4. **오늘 재기동 6회 + 크래시 1회.** 자정을 넘긴 늦은 시간이기도 하니, 다음 실기동 전
   사용자와 계속 여부를 반드시 확인할 것.

## 16. 🚨 일곱 번째 재실기동(2026-07-17) — §11과 동일한 로그인 차단 재발. 오늘은 여기서 중단

document 스코프 실험(§15-4)을 검증하려던 일곱 번째 실행에서, **§11에서 봤던 것과 완전히
동일한 증상**이 재발했다: 로그인 폼이 안 뜨고 무한로딩, 트레이스엔 `auth.band.us/s/login/getKey`의
`Uncaught` 예외와 `authOk` 미수신만 남음(§11의 로그와 문자 그대로 동일한 URL 패턴).

**§11과의 결정적 차이**: §11 때는 "밴드 접속정보 초기화 + 재시도 1회"로 즉시 풀렸다. 오늘은
그 초기화 이후로 이미 5번을 더 재기동했고(4~6차 성공, 그리고 지금 7차에서 재발) — **재시도로
한 번 풀린다고 그 뒤로도 계속 안전하다는 뜻이 아니라는 게 확인됐다.** 오늘 하루 총 7회
재기동(+ 어제까지 합치면 20회 넘음) 누적이 다시 임계치를 건드린 것으로 보인다 — §8-1
가설 4(세션 누적 피로/서버 스로틀링)가 사실상 확정에 가까워졌다.

**이번엔 재시도하지 않고 여기서 멈춘다.** §11 때처럼 "정보 초기화 → 바로 재시도"를 또
반복하면 오히려 차단을 더 굳히거나 계정 잠금으로 이어질 위험이 실재한다(브리프 §0).

### 16-1. 다음 세션이 반드시 지킬 것

1. **최소 몇 시간, 가능하면 하루 이상 쉬었다가 재시도할 것.** 오늘처럼 "막히면 초기화하고
   바로 재시도"를 반복하는 패턴 자체가 문제일 수 있다 — 초기화가 매번 통하는 게 아니라
   운이 좋았을 뿐일 수 있다.
2. 재시도할 때는 **한 세션에 재기동을 최대한 적게**(이상적으로는 1~2회) 쓰도록 미리 계획하고
   시작할 것 — 오늘은 세션당 재기동 수를 계속 "일단 하나 더" 식으로 늘려온 것 자체가
   문제를 키웠을 수 있다.
3. §15-4의 document 스코프 실험은 **아직 검증 못 함** — 코드는 이미 반영돼 있다
   (`acquire/collector.js`의 `clickLoadMoreComments`). 다음 세션이 로그인만 되면 바로
   결과를 볼 수 있다.
4. 로그인이 막히면 §11-2처럼 일반 브라우저로 band.us 정상 로그인이 되는지부터 확인해
   "이 세션/IP만 걸린 것"인지 "계정 자체 문제"인지 가른다.

## 17. 여덟 번째 재실기동(2026-07-17) — 사용자 판단으로 즉시 재시도, 로그인 정상. document 스코프 가설도 기각

§16 직후 사용자가 "재기동 자체는 문제없다"고 판단해 바로 재시도하기로 결정했다. 로그인은
이번엔 막힘 없이 정상 진행됐다(§16의 차단이 영구적이지 않다는 뜻 — 다만 재발 가능성 자체는
여전히 실재하므로 §16의 교훈은 유효하게 남겨둔다).

### 17-1. 결과: document 전체를 뒤져도 버튼이 없다 — 스코프 가설 확정 기각

`postsCommentsComplete: 40/46`, 실패 6건: 45·43·33·**32**·23·16 (기존 5건 + 이번엔 항상
성공하던 32도 실패). `clickLoadMoreComments`를 `document` 전체 검색으로 바꿨는데도
(`scopeIsDocument:true`) 실패한 글들은 **여전히 matchCount:0**였다 — 이제 "스코프가 잘못된
조상을 잡는다"는 §15-3의 가설은 확정적으로 기각됐다. `document` 전체에서 찾아도 "이전 댓글"
버튼이 정말 존재하지 않는다.

`broadCommentTexts`도 이번엔 document 전체 검색이라 피드의 다른 글 텍스트까지 섞여 나왔지만
(`"댓글18"`, `"댓글46"` 등 — 다른 글의 댓글수 배지), **페이지네이션 관련 텍스트는 여전히
전무**했다.

### 17-2. 지금까지 기각된 것 정리와 다음 방향

기각됨: 클릭 이벤트 종류(§13-6), 클릭 타이밍(§13-7/14), 클릭 탐색 스코프(§15-3/17-1).
**남은 결론**: 클릭 관련 어떤 변수를 조정해도 안 바뀐다는 건, 이 버튼이 **band.us
프론트엔드 자체의 렌더링/상태 로직에서 애초에 생성되지 않는 경우가 있다**는 뜻이다 —
우리 쪽 클릭 방식·시점·탐색 범위 문제가 아니라, **밴드 자체가 "이 글은 더 로드할 게 없다"고
착각하고 있거나, 그 트리거가 클릭이 아닌 다른 방식(예: 진짜 스크롤 이벤트 기반 무한스크롤,
클릭이 아니라 IntersectionObserver 같은 것)일 가능성**이 가장 유력해졌다.

다음에 시도할 것(클릭 관련 변수는 이제 다 소진했으므로 방향을 바꿔야 함):
1. **클릭을 완전히 버리고 진짜 스크롤 기반으로 전환.** `SCROLL_SCRIPT`를 모달 전체가 아니라
   **댓글 리스트 컨테이너 자체**를 특정해 그 컨테이너 안에서 위/아래로 실제
   `wheel`/`scroll` 이벤트를 여러 번 나눠 쏴보는 방식(한 번에 끝까지 스크롤하지 말고,
   실제 사람처럼 여러 스텝으로) — band.us가 IntersectionObserver 기반 무한스크롤을 쓴다면
   `scrollTop` 강제 대입만으로는 옵저버가 안 걸릴 수 있다(실제 스크롤 이벤트가 필요할 수
   있음).
2. `latest_comment`처럼(§7 참고) 밴드가 댓글 API 응답에 이미 더 많은 데이터를 내려주고
   있는데 우리가 못 읽는 필드가 있는지 재확인 — `data.total`이나 다른 페이지네이션 힌트
   필드를 원본 JSON 전체를 다시 훑어서 놓친 게 없는지 확인.
3. 이 5~6개 글이 왜 하필 얘네인지 규명은 잠시 보류 — 클릭 변수를 다 소진한 지금은 "왜 얘네만"보다
   "클릭이 아닌 다른 트리거 방식"을 먼저 검증하는 게 더 생산적일 것.

### 17-3. (경과 기록용, 아래 §21에서 최종 해결됨)

오늘 총 8회 재기동(+ 크래시 1회, 로그인 차단 1회) 시점의 중간 결론. 이후 §18~21에서 완전히
해결됐다.

## 18~20. 버그 B 최종 해결 과정 요약 (2026-07-17, 같은 세션 계속)

교수님 지시로 "오늘 안에 끝낸다"는 제약 아래 재기동을 계속하며 다음을 순서대로 시도·기각·확정했다
(총 19회 재기동 + 크래시 1회 + 로그인 차단 1회, 전부 같은 날 같은 세션):

1. **직접 fetch() 시도(§18)**: `previousParams`로 다음 페이지를 우리가 직접 fetch — 매번
   "권한이 없습니다" 인증 오류. 밴드 서버가 쿠키만으론 인증 안 하고 자체 서명/토큰이
   필요한 것으로 추정. **기각, 되돌림.**
2. **클릭 재시도 횟수 3→6 증가**: 효과 미미(같은 5개 글 반복 실패). **의미 없어서 3으로 되돌림
   (최종적으로는 §20에서 다시 조정).**
3. **가상 스크롤(scrollCommentsIncrementally)**: 스크롤 대상 탐색 휴리스틱이 자식 0개짜리
   유령 요소를 잘못 골랐던 버그 발견·수정(`div, main, section` → `*` + `children.length>0`
   필터). 수정 후에도 실패 지속 — 스크롤 자체가 원인이 아니었음.
4. **DOM 스냅샷 직접 확인**: 실패 글들의 "댓글" 관련 텍스트를 전부 긁어봐도 페이지네이션
   관련 텍스트가 전무 — 텍스트 매칭 자체의 한계를 드러냄.
5. **사용자 실측 개입 — 결정적 전환점**:
   - "이전 댓글"과 "다음 댓글 보기"는 서로 다른 흐름(전자는 반복 클릭형 페이지네이션,
     후자는 "첫 댓글로" 이후에만 나타나는 별개 UI)이라는 정정을 받음 — AI가 둘을 혼동했었음.
   - **"스크롤이 '이전 댓글' 버튼을 화면 밖으로 밀어낸다"**는 지적 — 클릭과 스크롤을 매
     시도마다 같이 하던 게 스스로 다음 클릭 기회를 망가뜨리고 있었음. **클릭 우선, 스크롤은
     못 찾을 때만 마지막 수단으로 쓰도록 순서 수정.**
   - **"지금까지의 클릭이 진짜 클릭이 맞는가?"**라는 질문 — `element.click()`/
     `dispatchEvent()`는 전부 `isTrusted:false`인 합성 이벤트라는 걸 지적받음. Electron
     `webContents.sendInputEvent`로 Chromium 입력 파이프라인에 실제 마우스
     다운/업을 주입하는 `realClickAt()`으로 교체.
   - 그래도 남동명의 글에서 "버튼을 아예 안 누르고 넘어가는" 현상 재현 — 35초 연속 전수
     검색으로 "이전 댓글" 텍스트가 DOM에 단 한 번도 없었음을 확정.
   - **사용자가 직접 DevTools로 실제 selector를 확인해줌**: `.moreComment` 클래스를 가진
     div가 "이전 댓글"류 트리거가 있는 글에는 항상 있고 없는 글에는 절대 없다. 텍스트 정규식
     매칭을 전부 버리고 이 selector로 교체 — **이게 근본 해결책이었다.**

### 20-1. 마지막 두 버그(스코프·완료판정)와 최종 수정

- **스코프 버그**: `document.querySelector('.moreComment')`(첫 번째 것)를 그대로 쓰면 이미
  닫힌 이전 글이나 피드의 다른 카드에 남은 무관한 `.moreComment`를 잘못 집어, 이미 완결된
  글(예: post_no=46, comment_count=13 전량 확보)까지 "더 있다"고 착각해 헛클릭·타임아웃을
  유발했다. **화면에 실제로 보이는 것 중 DOM상 마지막(모달이 나중에 붙는 오버레이라는 가정)
  것만 고르도록 수정.**
- **완료판정 버그**: `.moreComment`를 클릭해 없앤 뒤에도, 그 "없어짐"을 완료 신호로 받아들이는
  코드 경로가 없어서 재시도만 하다 타임아웃 나던 버그. `.moreComment`가 사라졌음을 확인하는
  즉시 `topLevelDone=true`로 완료 처리하도록 수정.
- **`total` 필드가 부풀려져 있다는 것도 재확인**: post_no=35(13/34), 34(14/20), 28(10/13),
  22(9/18), 3(15/23) 전부 **API 자체가 `previousParams:null`로 이미 완결 처리**했는데
  `total`만 실제보다 큰 값이었다 — §12-2에서 이미 밝힌 "total은 못 믿는다"는 결론이 다시
  한번 확인됨. 반대로 진짜 페이지네이션이 성공한 post_no=16(5페이지, 20+0+20+0+12=52건)은
  `total=52`와 정확히 일치 — total은 실제 데이터가 다 모이면 결국 맞는 값이라, "믿을 수
  없다"기보다는 "완결 판정에 쓰기엔 부적절하다(previousParams만 신뢰)"는 게 정확한 표현.

## 21. 최종 검증(2026-07-17, 19번째 재기동) — 버그 B 완전 해결 확정

`postsCommentsComplete: 52/52`, **경고 0건**, `feedExhausted:true`(전체 자연 완주). 원래
문제였던 5개 글도 이번엔 `.moreComment` 클릭으로 실제 추가 페이지를 성공적으로 받아왔다
(post_no=16: 5페이지 만에 52/52 정확히 일치). 오늘 밤 내내 쫓던 버그 B가 **완전히, 검증까지
끝나며 해결됐다.**

**핵심 교훈 — 다음에 비슷한 문제를 만나면**:
1. 텍스트 매칭보다 실제 DevTools로 확인한 CSS 클래스/selector가 압도적으로 신뢰도 높다 —
   사용자의 실측 개입이 없었다면 오늘 밤 내내 텍스트 정규식만 다듬고 있었을 것이다.
2. `element.click()`/`dispatchEvent()`는 `isTrusted:false`다. 사이트가 실제 사용자 입력을
   구분하는 경우, `webContents.sendInputEvent`(Electron) 같은 진짜 입력 주입이 필요할 수
   있다.
3. 클릭과 스크롤을 같은 루프에서 항상 같이 하면 서로의 전제(예: 타깃이 화면에 남아있어야
   클릭 가능)를 깨뜨릴 수 있다 — 순서를 신중히 설계할 것.
4. `document`-wide selector 검색은 스코프를 좁히지 않으면 무관한(닫힌 모달, 다른 카드의)
   요소를 잘못 집을 수 있다 — "화면에 보이는 것 중 마지막" 같은 필터가 필요할 수 있다.
5. API의 `total`/게시글의 `comment_count` 필드와 실제 페이지네이션으로 받아지는 데이터量이
   다를 수 있다 — `previousParams`(또는 동급의 페이지네이션 커서)만 신뢰할 것.

**다음 단계**: ~~M1 acquire 단계는 이제 완료됐다고 봐도 된다~~ → **§22에서 정정: 아직 아니다.**
raw 파일 저장 여부를 재확인하기 전까지는 완료 선언 보류.

## 22. 🚨 세션 종료 직전 발견 — 트레이스는 성공을 보여주는데 raw 파일엔 반영이 안 됨(원인 미해결)

§21의 "52/52 성공" 직후, 사용자가 "크롤링이 놓치는 정보 없이 잘 가져오는지 확인하고 싶다"고
요청해 검증 스크립트(`scripts/verify_comment_counts.js`, 아래 §22-3)를 준비하다가 **훨씬 심각한
문제**를 발견했다. **이 문제 때문에 §21의 "M1 완료" 선언은 취소한다** — 다음 세션이 반드시
가장 먼저 풀어야 할 이슈다.

### 22-1. 증상

- `data/raw/103239777/`의 모든 `items.ndjson` 파일의 최종 수정 시각은 **2026-07-16T14:54:23Z**다
  (node `fs.statSync(...).mtimeMs`로 정밀 확인).
- 오늘 세션의 **첫** 재기동조차 그보다 늦은 시각(약 15:35Z)에 시작했고, "52/52 성공"한 마지막
  실행은 **19:56:26Z**에 끝났다. 즉 **성공했다는 실행이 끝나고 5시간 전이 마지막 파일 쓰기
  시각** — 오늘 밤의 어떤 재기동도 댓글 데이터를 raw 파일에 새로 쓰지 않았다.
- 그런데 오늘 밤 내내 트레이스(`phase:'emit', eventName:'commentPage'`)는 실제 데이터
  개수(예: post_no=16이 5페이지에 걸쳐 20+0+20+0+12=52건, `total`과 정확히 일치)를 정확히
  보여줬다 — **인터셉터가 응답을 정상적으로 파싱·emit은 했다는 뜻.**

### 22-2. 지금까지 배제한 것 (다음 세션이 다시 확인할 필요 없음)

- **`writer.writeComment()` 자체는 정상 작동한다.** 직접 단위 테스트로 확인:
  ```js
  const { createWriter } = require('./acquire/writer');
  const w = createWriter({ rawDir: 'data/raw', bandId: '103239777' });
  w.writeComment({ comment_id: 999999999, created_at: Date.now(), post_no: 16, content: 'TEST-PROBE' },
    { contentType: 'post', parentCommentId: null, postNo: 16, sourceUrl: 'test' });
  ```
  → `data/raw/103239777/2026-07-17/items.ndjson`에 정상적으로 새 줄이 추가됨(`isNew:true`).
  **저장 함수 자체는 결백하다.**
- **최상위 댓글 `comment_id`가 글마다 겹쳐서(dedup 키 충돌로) 조용히 유실되는 것도 아니다.**
  `commentDedupKey()`가 최상위 댓글은 `post_no` 없이 `String(comment_id)`만 쓰는 게 이론상
  위험해 보여 의심했으나, 실측 데이터(`post_no=27`은 id 1~10, `post_no=25`는 11~15,
  `post_no=23`은 16~21, `post_no=47`은 22~32, `post_no=1`은 33~52, `post_no=33`은 53~54)를
  까보니 **밴드의 `comment_id`는 실제로 밴드(또는 최소 이 게시판) 전체에서 전역 유일하게
  순차 부여되는 것으로 보인다** — 글 사이 충돌 0건 확인. 이 가설은 기각.
- 기존 raw 데이터에 실제로 남아있는 최상위 댓글은 **post_no 1·23·25·27·33·47 여섯 개뿐**이고
  (총 55건, 위 테스트 프로브 1건 제외), 나머지 40여 개 글은 최상위 댓글이 단 하나도 없다 —
  이게 오늘 이전, 아주 초기 세션(댓글 캡처가 막 되기 시작했을 때)의 잔재로 보인다.

### 22-3. 다음 세션 검증 도구(이미 준비됨)

`scripts/verify_comment_counts.js` — `data/raw/<bandId>/*/items.ndjson`을 전부 읽어 post_no별
실제 캡처된 최상위/답글 댓글 수를 집계해 CSV로 뽑는다.
```
node scripts/verify_comment_counts.js [bandId]   # 기본 bandId=103239777
```
출력: `out/verify/captured_comment_counts_103239777.csv`
(컬럼: post_no, author, created_at_kst, band_comment_count, captured_top_level,
captured_replies, captured_total, manual_count, diff — 마지막 두 칸은 사용자가 직접 채워
넣을 빈 칸). **이미 한 번 실행해 최신 raw 데이터 기준으로 생성해뒀다** — §22-1의 버그 때문에
지금 이 CSV의 captured_* 값은 대부분 0에 가까울 것이다(재현됨).

### 22-4. 다음 세션이 조사할 순서 (재기동 없이 먼저 시도할 것들)

1. **`comment.created_at`의 실제 타입 확인.** band API 응답의 댓글 객체에서 `created_at`이
   숫자(epoch ms)가 아니라 문자열이면, `kstDateStr(ms)`가 `new Date(ms + 9*3600*1000)`에서
   `ms`가 문자열일 때 `+`가 문자열 접합으로 동작해(JS의 `+`는 피연산자 중 하나라도 문자열이면
   숫자 덧셈이 아니라 문자열 이어붙이기) `Invalid Date`가 될 수 있다 — 그러면
   `appendLine`이 이상한 경로에 쓰거나 예외를 던질 수 있다. `logs/audit/`의 최신 로그나
   `data/raw/103239777/<bandId>` 아래 이상한 이름의 폴더가 생겼는지부터 재확인
   (§22-1 조사 시점엔 없었음 — 그 이후 재확인 필요할 수도).
2. **`interceptor.js`의 `handleCapture`/`handleCommentList`가 예외를 던지고 있는지 확인.**
   `cdp-capture.js`의 `Fetch.requestPaused` 핸들러는 `interceptor.handleCapture(...)` 호출을
   try/catch로 감싸는데, 이 catch가 "[cdp] getResponseBody 실패"로 로그를 남기므로 —
   최근 실기동 로그(`logs/audit/run_*.log`)에서 이 문자열이 댓글 응답 URL과 함께 등장하는지
   grep으로 확인. **재기동 없이 기존 로그만으로 확인 가능.**
3. **`BSC_TRACE=1`에 `writer.writeComment`의 반환값(`isNew`)과 `comment.created_at` 타입을
   추가로 남기도록 계측 확장.** `interceptor.js`의 `handleCommentList` 루프 안에
   `trace.record({ phase: 'writeComment', postNo, commentId: c.comment_id, isNew,
   createdAtType: typeof c.created_at, createdAt: c.created_at })`를 추가하면, 다음
   재기동 한 번으로 "writeComment가 호출은 되는지", "isNew가 true인지 false인지",
   "created_at이 정상적인 숫자인지"를 한 번에 확인할 수 있다. **이게 가장 직접적인 다음
   진단이다.**
4. 원인이 밝혀지면 고치고, `scripts/verify_comment_counts.js`를 다시 돌려 raw 파일에 실제로
   반영됐는지 확인.
5. 그다음에야 사용자가 원래 요청한 작업(§1의 수동 확인한 1~48번 게시글 댓글 수 vs
   `captured_total` 비교)을 진행한다 — CSV의 `manual_count` 칸에 사용자가 직접 확인한 값을
   채우고, `diff = manual_count - captured_total`을 계산해 어긋나는 글을 찾는다.

### 22-5. 오늘 세션 총평

재기동 총 19회 + 크래시 1회 + 로그인 차단 1회. 버그 A(이벤트 버스 레이스)와 버그 B(페이지네이션
트리거)는 완전히 해결·검증됐다. 하지만 그 결과가 실제로 디스크에 반영되는지는 **미해결 상태로
세션이 끝난다** — 다음 세션은 §22-4의 순서대로 이어가면 된다.

## 23. 새 머신(WSL/CLI) 세션(2026-07-20) — §22의 "raw 파일 미반영" 의혹은 버그 아님, 오진으로 결론

작업 환경이 Windows Claude Code 데스크톱 앱에서 WSL2 + Claude Code CLI로 바뀌었다(사람은 WSLg로
창을 계속 볼 수 있음, AI는 CDP `Page.captureScreenshot`으로 스크린샷을 찍어 파일로 저장 후
Read 도구로 직접 확인하는 방식을 새로 갖췄다 — `acquire/capture/cdp-capture.js`의
`screenshot()`, `acquire/collector.js`의 `shot()`/`withPeriodicScreenshots()` 참고). 프라이빗
데이터 저장소(`band-score-capture-data`)에서 `data/`·`input/`·`out/`·`logs/`를 그대로 복사해
받아온 뒤 §22-4의 조사 순서(재기동 없이 먼저 시도할 것들)를 그대로 따랐다.

### 23-1. 재기동 없이 트레이스만으로 원인 확정

**1단계(로그 grep)**: 마지막 52/52 세션(`logs/audit/run_1784238928823.log`)에
`get_comments` 관련 `getResponseBody 실패`가 없음을 확인 — §22-4-2 가설(interceptor 예외 삼킴)
기각.

**핵심 발견**: 같은 세션의 트레이스(`logs/trace/trace_103239777_1784238929193.ndjson`)를
`phase:'writeComment-summary'`로 집계하면 `writeNewCount` 합계가 **정확히 0**, `writeDupCount`
합계가 **683**이었다. 즉 이 세션이 만난 모든 댓글이 이미 파일에 있던 것으로 정확히 dedup
처리됐다는 뜻 — `writer.writeComment()`가 안 불렸거나 실패한 게 아니라, **애초에 새로 쓸 게
없었다.**

같은 날 저녁의 다른 트레이스 파일들을 시간순으로 같은 방식으로 집계하니 그림이 완전히
드러났다:

| 트레이스 파일(타임스탬프) | writeNewCount 합 | writeDupCount 합 |
|---|---|---|
| trace_..._1784234092160 | **629** | 54 |
| trace_..._1784235973505 | **8** | 675 |
| trace_..._1784236458317 | 0 | 683 |
| trace_..._1784236921658 | 0 | 683 |
| trace_..._1784237314844 | 0 | 683 |
| trace_..._1784238398559 | 0 | 683 |
| trace_..._1784238929193 (§21의 "52/52" 세션) | 0 | 683 |

즉 진짜 캡처(신규 기록 629+8=637건)는 그날 저녁 **앞선 두 번의 재기동**에서 이미 끝났고,
그 뒤에 있었던 재기동(52/52 세션 포함) 다섯 번은 전부 같은 데이터를 다시 훑으며 100%
dedup된 것뿐이다 — **이건 정상 동작이지 버그가 아니다.** §22-1이 "raw 파일 mtime이
세션 시작보다도 오래됐다"고 관찰한 것 자체는 사실이었겠지만, 그걸 "쓰기 실패"로 해석한 게
오진이었다 — 파일이 안 바뀐 이유는 "쓸 새 데이터가 없었기 때문"이다.

### 23-2. 현재 raw 데이터 상태 직접 검증 (2026-07-20 기준)

`data/raw/103239777/`의 모든 `items.ndjson`을 훑어보면 `schemaType:"comment"` 레코드가
968건 있고, **전부** `data.created_at`이 숫자(epoch ms)다 — §22-4-1의 "created_at이 문자열일
수 있다" 가설도 이걸로 기각(적어도 현재 저장된 데이터 안에서는 문자열 사례 0건).

`node scripts/verify_comment_counts.js`를 재실행해 `out/verify/captured_comment_counts_103239777.csv`를
새로 뽑았다 — §22-3이 예측했던 "captured_* 값이 대부분 0"과 반대로, **48개 글 전부 captured_total이
채워졌다**(밴드 자체 댓글이 0건인 post_no=11·36만 0, 나머지는 전부 실측값 있음).

**단 하나 남는 이상 신호**: `post_no=33`(황인각)만 `band_comment_count=51`인데
`captured_total=20`으로 큰 격차(-31)가 있다. 다른 글들은 대부분 captured가 band_count와
같거나 더 크다(band 쪽 `comment_count` 필드가 신뢰 불가라는 건 §12-2/§20-1에서 이미 확정됨 —
보통은 band 쪽이 과소산정). post_no=33만 반대로 band가 훨씬 크다는 게 특이해서, 이 글은 진짜
결손일 가능성을 배제 못 한다 — 다음 사람이 확인할 때 후순위 아이템이 아니라 **1순위로 확인**
할 것.

### 23-3. 결론 및 다음 단계

- §22가 열어둔 "raw 파일이 실제로 갱신되는가"라는 질문은 **닫혔다** — 갱신되고 있었고, 지금
  디스크에 있는 데이터는 진짜다. `comment.created_at` 문자열 가설도 기각됐다. **재기동은
  0회** — 기존 로그/트레이스/verify 스크립트만으로 결론 났다.
- 이제 next-session-prompt.md §6(=이 파일 §22-4-5)로 넘어갈 차례: 사용자가 1~48번 글의 댓글
  개수를 직접 세서 CSV의 `manual_count` 칸을 채우면, `diff = manual_count - captured_total`로
  최종 검증한다. **post_no=33은 특히 우선 확인 대상.**
- M1은 아직 "완료 선언" 전이다 — manual_count 대조가 끝나야 최종 완료.

## 24. 같은 세션(WSL/CLI) 계속 — 사용자 제공 정답(1~63번, 실측 카운트)으로 실기동 1회 + 마지막 버그 발견·수정

사용자가 직접 웹에서 센 1~63번 게시글의 댓글 수 전체를 정답으로 제공했다(§1의 61개 + 후속
정정 12개). 이 정답과 실기동 결과를 대조해 §22의 "raw 미반영" 의혹을 완전히 종결하고, 마지막
남은 실제 버그(대댓글 "더보기" 버튼) 하나를 특정·수정했다.

### 24-1. 실기동 1회(로그인 1회) — `postsCommentsComplete: 53/53`, 재기동 없이 트레이스만으로
### §22의 미해결 의혹부터 재검증

새 raw 데이터(트레이스 `trace_103239777_1784238929193.ndjson` 등, private 데이터 저장소에서
가져옴)를 분석한 결과 §22가 우려했던 "raw 파일 미반영"은 **버그가 아니라 오진이었다** —
`writeComment-summary`의 `writeNewCount`/`writeDupCount`를 트레이스 파일별로 시간순 집계하면
그날 저녁 앞선 두 재기동(629건, 8건 신규 기록)에서 이미 캡처가 끝났고, 그 이후 재기동들(52/52
세션 포함)은 전부 이미 다 받은 데이터를 다시 순회하며 100% dedup된 것뿐이었다. `created_at`
문자열 가설도 기각(968건 전부 숫자 확인). 재기동 0회로 결론남.

### 24-2. 실기동으로 확인된 것

- **post_no 33, 46**(황인각 교수님, 사진 첨부로 본문이 긴 글) — 지난 세션엔 대량 결손이었는데
  (33: 20/51, 46: 14/51) 이번 실기동에서는 기존 스크롤 폴백(`scrollModalDownOnce`/
  `pollForLoadMoreTarget`)만으로 **완전히 해결됨**(둘 다 51/51). 별도 코드 수정 없이 자연
  해결 — §2a의 "본문이 길어 트리거가 화면 밖" 가설에 대한 기존 대응이 이미 충분했던 것으로
  보인다(§13-3에서 우려했던 "클릭해도 요청이 안 나감" 케이스는 이번엔 재현 안 됨 — 그때는
  타이밍 문제였을 가능성).
- **post_no 51, 57 결번**: 밴드 자체에 이 두 번호가 없다(삭제됐거나 애초에 일반 게시글이
  아니었을 가능성). 순회는 `.btnNextPost`로 실제 피드를 넘기는 방식이라 존재하지 않는 글은
  자연스럽게 건너뛴다 — 수집 버그 아님. 이 결번 때문에 51번 이후 게시글은 "밴드 post_no"와
  "사용자가 수동으로 센 N번째 글"이 어긋나 보였을 뿐, 정렬만 다시 맞추면(사용자가 50번째 글부터
  다시 확인해준 값과 대조) 전부 정확히 일치했다.
- **post_no 47~63(신규 글 포함) 전부 사용자 정답과 정확히 일치.**
- **post_no 14만 유일하게 실제 결손**(정답 28, 캡처 26) — 원인 규명은 §24-3.

### 24-3. 마지막 버그 특정: `.moreReply._openReplyListBtn`("N개의 답글 더보기") 미클릭

사용자가 직접 CDP 원격 디버깅(`--remote-debugging-port`)으로 연 창에서 **수동으로 post_no=14로
이동**해 화면을 보여줬고, 그 상태를 Node의 내장 `WebSocket`으로 CDP에 직접 연결해
`Runtime.evaluate`로 DOM을 덤프해 확인했다(스크린샷도 동시에 확인 — 폰트 미설치 시 한글
본문이 깨져서 `fonts-nanum`/`fonts-noto-cjk` 설치 후 재확인함, 짧은 UI 문자열(날짜 등)은
폰트 없이도 렌더링됐지만 긴 본문은 안 됐었다).

**원인**: `latest_comment`로 딸려오는 답글 수보다 실제 답글이 더 많은 부모 댓글에는
`.moreReply._openReplyListBtn` 버튼(텍스트: "N개의 답글 더보기")이 붙는데, 이건
`scrollThroughModal`이 트리거하는 "화면 밖이라 렌더 안 됨" 문제와는 별개의, **명시적 클릭이
필요한 트리거**다. post_no=14는 화면에 이미 다 렌더돼 있었는데도(스크롤 문제가 아님) 이 버튼을
안 누르면 답글 2개가 영영 안 잡혔다.

**수정**(`acquire/collector.js`): `findReplyExpandButtons()`(`.moreReply._openReplyListBtn`
탐색, 모달 스코프 한정)와 `expandHiddenReplies()`(찾은 버튼을 하나씩 `realClickAt`으로 실제
클릭 → `commentPage`(contentType:'comment') 응답 대기 → 재탐색, 최대 30라운드)를 추가하고,
`collectCommentsInOpenModal()`에서 `scrollThroughModal()` 직후에 호출하도록 연결했다. 버튼을
한 번에 하나씩만 클릭하는 이유: 클릭 한 번에 그 스레드의 답글이 DOM에 추가되며 아래쪽 다른
버튼들의 좌표가 밀릴 수 있어, 클릭마다 좌표를 다시 구하는 게 안전하다(기존 `.moreComment`/
`.btnNextPost` 클릭 로직과 동일한 이유로 synthetic `.click()` 대신 `realClickAt` 사용 —
§19-3). `node --check` 통과. **아직 실기동 검증 전.**

### 24-4. 다음 세션이 할 일

1. `BSC_TRACE=1 npx electron .`로 1회 실기동해 `postsCommentsComplete`가 전체(post_no 51·57
   결번 감안한 실제 대상 수)에서 100%가 되는지, 특히 **post_no=14가 28/28로 완결되는지**
   확인한다.
2. `.moreReply._openReplyListBtn`이 한 부모 댓글당 여러 개 중첩될 수 있는지(예: 답글의
   답글) 아직 실측 안 됨 — 실기동에서 `phase:'moreReplyClick'` 트레이스가 몇 라운드
   반복되는지로 확인 가능.
3. 여기까지 되면 M1 acquire는 데이터 정확성 기준(§1의 최종 합격 테스트)까지 충족 — scoring(M2)
   으로 넘어갈 차례.

## 25. 같은 세션 — "몰랐던 실패"를 없애는 안전장치 추가 (2026-07-20)

`.moreReply` 버튼 수정(§24-3)을 재실기동으로 검증했으나 post_no=14는 여전히 재현되지 않고
남았다(스크롤 전/후 둘 다 버튼 0건 — 사람이 수동 탐색할 때와 자동화(`.moreComment` 반복 클릭
직후) 사이에 화면 상태가 미묘하게 달라 보인다, 원인 미확정). 사용자가 이 지점에서 방향을
정정했다: **"수집하지 못하는 것"은 실패가 아니다. "수집하지 못했다는 것도 모르는 것"이
실패다.** 즉 100% 자동 수집을 계속 쫓기보다, 놓친 부분을 사람이 정확히 알고 수동으로 메울 수
있게 만드는 쪽으로 우선순위를 바꿨다.

### 25-1. 문제였던 것

기존엔 결손이 생기면 `logger.warn()` 한 줄(`대댓글 미소진 부모 댓글 N건`)로만 남았다 — 이건
`logs/audit/*.log`를 사람이 직접 읽어야만 보이고, **정확히 어느 댓글(parentCommentId)이
부족한지, 그 글의 URL이 뭔지는 로그에 없었다.** `data/raw/`의 raw ndjson만 보는 사람이나
스크립트(scoring 등)는 이 결손의 존재 자체를 알 방법이 없었다.

### 25-2. 추가한 것

- `acquire/collector.js`: `collectCommentsInOpenModal()`이 최상위 페이지네이션 결손
  (`topLevelGap: {expected, captured}`)과 대댓글 결손(`repliesStatus`에 `parentAuthor` 추가)을
  구조화해서 반환하도록 확장. `walkPostsViaModal()`이 이걸 모아 `gaps[]` 배열을 만든다(각
  항목에 `type`, `postNo`, `postAuthor`, **`postWebUrl`**, `parentCommentId`/`parentAuthor`,
  `expected`/`captured`/`missing` 포함 — 사람이 클릭 한 번으로 그 글에 갈 수 있게).
- `acquire/writer.js`: `writeIncompleteGaps(gaps)` 추가 — 매 실행마다
  `data/raw/<bandId>/incomplete_gaps.json`을 **그 시점 기준 전체로 덮어쓴다**(append 아님 —
  다음 실행에서 고쳐지면 이 파일에서도 사라져야 "아직 안 고쳐짐"과 "이미 고쳐짐"이 안 헷갈림).
- `acquire/collector.js`의 `runBandCollection()`: 결손이 하나라도 있으면 일반 INFO 로그에
  묻히지 않도록 별도 WARN으로 파일 경로까지 명시(`⚠ 알려진 결손 N건 — ... incomplete_gaps.json`).
  0건이면 그것도 명시적으로 로그(`알려진 결손 0건 — 데이터 완전성 확인됨`) — "결손 로그가 안
  보인다"와 "결손이 없음을 확인했다"를 구분하기 위함.
- 신규 `scripts/list_incomplete_gaps.js`: `incomplete_gaps.json`을 읽어 사람이 바로 읽을 체크
  리스트(글 URL 포함)를 콘솔에 찍고, `out/verify/manual_followup_<bandId>.csv`(컬럼:
  type/post_no/post_author/post_url/parent_comment_id/parent_author/expected/captured/missing/
  **manual_value**/**note** — 마지막 두 칸은 사람이 직접 확인한 값·메모를 채우는 빈 칸)로도
  저장한다.
- 합성 데이터(post_no=14의 실제 결손 값)로 `writer.writeIncompleteGaps()`와
  `list_incomplete_gaps.js` 양쪽 다 단위 테스트 완료. `node --check` 전체 통과. **실기동으로
  전체 파이프라인(collectCommentsInOpenModal → gaps 수집 → 파일 기록)이 실제로 맞물려 도는지는
  아직 검증 전.**

### 25-3. 다음 세션이 할 일

1. 실기동 1회로 `data/raw/103239777/incomplete_gaps.json`이 실제로 생성되고 post_no=14가
   여기 잡히는지 확인.
2. `node scripts/list_incomplete_gaps.js`로 체크리스트가 정상 출력되는지 확인.
3. 이후부터는 이 파일이 0건이 아니면 M2(채점) 스크립트가 **그 학생/글을 자동으로 채점에서
   빠뜨리지 않고 사람에게 명시적으로 확인을 요구**하도록 설계할 것 — §1의 "단 하나라도 놓치면
   안 된다"는 원칙은 "자동으로 100% 수집"이 아니라 "놓친 걸 반드시 알고 사람이 메운다"로
   재해석됐다(사용자 확인, 2026-07-20).

## 26. 같은 세션 - Windows 렌더링 대비 특수문자 제거 + 신뢰도 체계 도입 + 3단계 교차검증 구현 (2026-07-20)

### 26-1. 특수문자 제거

이 프로그램은 높은 확률로 Windows에서 실행된다(사용자 지적) - 콘솔/로그 출력에 픽토그램류
유니코드(⚠ 등)가 있으면 렌더링이 깨질 수 있다. `acquire/collector.js`의 런타임 로그 문자열에서
`⚠` 1건과 화살표(→) 3건을 ASCII(`[경고]`, `-`)로 교체했다. 코드 주석에 남은 화살표 2건은
사람이 에디터로만 보는 텍스트라 실제 출력엔 안 나가므로 그대로 뒀다. 전체
`acquire/`·`scripts/`·`lib/`를 재검색해 픽토그램류가 더 없음을 확인했다.

### 26-2. 신뢰도 체계 공식화 (`CLAUDE.md`에 영구 기록)

사용자가 "우리가 결손을 어떻게 판단하는가"라는 질문에 답하며 4단계 신뢰도 체계를 규정했다:
1. 사람이 직접 눈으로 확인(유일한 진짜 외부 정답 - 이 대화의 61/63개 게시글 수동 대조가 실례)
2. "인간 검증 바로 전" 단계 - 밴드 UI가 사람에게 보여주는 값 3가지:
   - 게시글 모달의 표시된 댓글 수(`.postCount>.postCountLeft>.faceComment>.comment` 계열)
   - 피드 전체를 끝까지 스크롤해서 센 `div.cCard.gContentCardShadow.-brunchOfPostType` 개수
     (공지 `data-viewname="DAnnouncementItemView"` 제외, `display:none` 제외)
   - 멤버별 총 댓글 수(멤버 → 아이콘 클릭 → 작성글 보기 → 댓글 탭 → 끝까지 스크롤) - 단 이건
     우리 코드가 수집하는 것이라 완전한 외부 독립검증은 아니고 내부 교차검증
3. 밴드 API의 `comment_count`/`total` 필드 - 이미 신뢰 불가로 확인됨(§12-2, §20-1) - 최후
   수단으로만
4. 우리 자신의 루프 종료 신호(`.moreComment`/`.moreReply` 버튼 부재) - "밴드 UI가 더 보여줄 게
   없다"는 뜻이지 "완전한 참 데이터를 확보했다"는 보증은 아님

`incomplete_gaps.json`의 각 항목에 `reason`/`reasonTier`를 추가해 어느 단계에서 걸린
불일치인지 구분한다(`scripts/list_incomplete_gaps.js`가 tier 오름차순 = 신뢰도 높은 순으로
정렬해 출력).

### 26-3. 구현한 것 (전부 `node --check` 통과, 플러밍은 합성 데이터로 단위 테스트, 실기동 검증 전)

- `readDisplayedCommentCount(win)`(2단계-1): 게시글 모달의 표시 댓글 수를 읽어
  `collectCommentsInOpenModal`의 캡처 총합(최상위+대댓글)과 비교. 불일치 시
  `type:'displayed-count-mismatch', reasonTier:2`로 gaps에 기록.
- `countTotalPostsViaFeedScroll(win)`(2단계-2): 피드를 실제 휠 스크롤로 끝까지 내리며
  카드 개수를 센다. `runBandCollection`에서 `feedExhausted`일 때만
  `walkResult.posts.length`와 비교, 불일치 시 `type:'total-post-count-mismatch',
  reasonTier:2`로 기록.
- `collectPerMemberCommentCounts(win, members, ...)`(2단계-3): 멤버 프로필 링크를 찾아
  하나씩 열고(`findMemberProfileLinks`) "작성글 보기"→"댓글" 탭을 텍스트 매칭으로 클릭한 뒤
  (`findClickableByText`) 끝까지 스크롤(`scrollLargestScrollableToBottom`)하고 표시된 수를
  읽는다(`readCountNearLabel`). **이 화면은 이번 세션에서 한 번도 실측한 적 없어 정확한
  selector를 확신 못 함** - 텍스트 매칭 위주로 방어적으로 짜고 각 단계를 전부 트레이스에
  남겼다. 비용이 커서(멤버 수만큼 클릭+스크롤) `BSC_VERIFY_MEMBERS=1`일 때만 실행되도록
  게이팅했다(`main.js`가 아니라 `runBandCollection` 안에서 직접 env var 체크).
- `writer.writeMemberCommentCounts()`: `data/raw/<bandId>/_members/member_comment_counts_
  <ts>.json`에 저장.
- 신규 `scripts/verify_member_comment_counts.js`: 위 파일과 raw ndjson에서 author별로 직접
  집계한 캡처 댓글 수를 대조해 `out/verify/member_comment_counts_<bandId>.csv`로 출력.
- `scripts/list_incomplete_gaps.js`: reason/reasonTier 표시 + tier 오름차순 정렬 추가.

### 26-4. 다음 세션이 반드시 실기동으로 확인해야 할 것 (우선순위순)

1. **`readDisplayedCommentCount`의 selector가 실제로 맞는지.** 사용자가 알려준 클래스
   체인이지만 코드로 옮기며 직접 실측은 안 했다 - 트레이스의 `phase:'readDisplayedCommentCount'`
   에서 `found:true`가 나오는지, `count` 값이 실제 화면 숫자와 일치하는지 확인.
2. **`countTotalPostsViaFeedScroll`의 selector.** `div.postWrap.viewTypeListWrap` /
   `div.cCard.gContentCardShadow.-brunchOfPostType` 이 실제 DOM과 맞는지, 공지 제외가 제대로
   되는지 - `phase:'feedScrollCount'` 트레이스로 확인.
3. **`collectPerMemberCommentCounts` 전체 흐름 - 가장 불확실함.** `BSC_VERIFY_MEMBERS=1`로
   딱 1~2명만이라도 먼저 확인해볼 것(57명 전체를 무작정 돌리지 말고). `findMemberProfileLinks`가
   프로필 링크를 제대로 찾는지, "작성글 보기"/"댓글" 탭 텍스트 매칭이 맞는지, 스크롤 후 읽은
   숫자가 실제 화면 값과 맞는지 - `phase:'memberVerify:*'` 트레이스 전부 확인.
4. 셋 다 확인되면 §1의 "최종 합격 테스트"를 이 세 신호로도 교차검증하면서 M1 acquire를 최종
   완료 선언할 수 있다.

## 26-5. 같은 세션 계속 — 사용자가 실시간으로 화면을 조작하며 §26의 세 selector 전부 실측 확정

사용자가 "네가 CDP로 직접 보면서 selector를 특정할 수 있는가"라고 물어 그렇게 진행했다. 이번엔
사용자가 직접 클릭하는 대신, `--remote-debugging-port`로 띄운 창을 Node 내장 `WebSocket`으로
직접 연결해 `Input.dispatchMouseEvent`/`Runtime.evaluate`/`Page.captureScreenshot`를 내가 직접
호출하며(사람이 마우스로 클릭하는 것과 동일하게 신뢰되는 입력) 단계별로 화면을 확인했다.

**확정된 것**:
- `.postCount>.postCountLeft>.faceComment>.comment`(사용자가 알려준 클래스 체인) — **정확히
  일치**. `<button class="comment _commentCountBtn">댓글<span class="count">7</span></button>`
  구조 확인.
- 게시글 카드 selector — 사용자가 말한 `div.postWrap.viewTypeListWrap` /
  `div.cCard.gContentCardShadow.-brunchOfPostType`는 **실제 DOM과 다름**(그런 클래스 없음).
  실제로는 그냥 `div.cCard.gContentCardShadow`뿐이고 `-brunchOfPostType` 수식자는 없다.
  공지는 `data-viewname="DAnnouncementItemView"`로 정확히 구분됨(사용자 말대로). `_popularPostListRegion`("인기 게시글")이라는 별도 섹션이 존재해 카드가 중복 집계될 수
  있어 제외 처리 추가. **실측 정확도 검증**: 전체 카드 67개 - 공지 6개 = 61개, 이게
  `.btnNextPost` 순회로 확인한 실제 게시글 수(post_no 1~63, 51·57 결번 제외 61개)와
  **정확히 일치**했다.
- 멤버별 댓글 수 — 사용자가 설명한 경로(멤버→아이콘→작성글 보기→댓글 탭→스크롤)를 그대로
  클릭해보며 확정:
  - 프로필 아이콘: `li[data-viewname="DMemberListItemView"] a.uProfile._btnProfile`(이름은
    안의 `img[alt]`).
  - "작성글 보기": `a.writePost._btnGotoSearchMemberContent` — 클릭 시 URL이
    `/band/<id>/member/<memberKey>/post`로 바뀜.
  - "댓글" 탭: `a.navItem`(게시글/사진/댓글 3개가 같은 class라 텍스트 정확히 매칭 필요) —
    클릭 시 URL이 `.../comment`로 바뀜.
  - **memberKey는 멤버 API 응답에 없다**(`user_no`/`name`/`role`/`created_at`/`online`/`me`
    뿐) — 그래서 URL을 미리 만들어 바로 이동하는 지름길은 불가능, 아이콘 클릭이 항상
    필요하다. 실제로 plain `user_no`로 URL을 만들어 시도해봤는데 그냥 피드로 리다이렉트됨
    (실패 확인).
  - **"총 댓글 수"를 보여주는 별도 라벨/배지는 없다.** 사용자가 "스크롤하면 전체 댓글 수가
    나온다"고 했지만 실측 결과 그런 요소는 없었고, 대신 **끝까지 스크롤한 뒤
    `a.cCommentOnly` 요소 개수를 세는 것 자체가 정답**이었다. 검증: 강민지 18개(raw
    데이터 집계도 18) 100% 일치, 황인각 1개(raw 데이터 집계도 1) 100% 일치.
  - 멤버 목록(57명)은 가상스크롤 없이 페이지 로드 시 전부 한 번에 렌더링됨(스크롤 불필요).
- `acquire/collector.js`를 위 실측 결과로 전부 교정: `countRenderedPostCards`(카드 selector
  수정), `findMemberProfileLinks`/`readOneMemberCommentCount`/`collectPerMemberCommentCounts`
  를 텍스트 매칭 방식에서 확정 selector 직접 사용 방식으로 재작성(`findClickableByText`/
  `scrollLargestScrollableToBottom`/`readCountNearLabel` 등 추측 기반 헬퍼는 전부 제거).
  `readOneMemberCommentCount`/`findMemberProfileLinks`/`collectPerMemberCommentCounts`/
  `countTotalPostsViaFeedScroll`을 테스트 가능하도록 `module.exports`에 추가.

**아직 완전히 못 끝낸 것**: `collectPerMemberCommentCounts`를 실제 Electron 프로세스 안에서
`readOneMemberCommentCount` 2명분(황인각·강민지) 호출로 end-to-end 테스트하려 했으나, 새
프로세스를 띄우자 이번엔 세션이 유지되지 않아(`LINKS_FOUND: 0`) 테스트를 못 끝냈다 —
**"persist 세션 재사용을 가정하지 말 것"이라는 이 프로젝트의 기존 교훈이 오늘 하루에만 여러 번
재확인됐다**(한 번은 됐고, 두 번은 안 됐다 — 예측 불가). 개별 selector 4개는 전부 실측
확인됐지만, 전체 흐름을 한 번에 이어 붙여 실행했을 때의 타이밍 이슈까지는 검증 못했다.

### 26-6. 다음 세션이 할 일

1. 로그인 후 `node_modules/.bin/electron <테스트 스크립트>`로 `collector.findMemberProfileLinks`
   + `collector.readOneMemberCommentCount`를 황인각·강민지 2명만 먼저 테스트(전체 57명 아님) —
   결과가 각각 1, 18이 나오면 성공.
2. 성공하면 `BSC_VERIFY_MEMBERS=1`로 실제 앱을 돌려 57명 전체 파이프라인이 안 끊기고 끝까지
   도는지 확인. `logs/trace/*.ndjson`의 `phase:'memberVerify:*'`로 실패 지점 진단.
3. `readDisplayedCommentCount`(2단계-1)와 `countTotalPostsViaFeedScroll`(2단계-2)는 selector
   자체는 이미 실측 확인됐지만, `collectCommentsInOpenModal`/`runBandCollection`의 실제 실행
   흐름 안에서(트레이스가 아니라 CDP 수동 조작으로 확인한 것이므로) 다시 한번 정식 실기동으로
   재확인할 것.

## 27. 같은 세션 - "전체 1사이클" 실기동 3회, 회귀 발견·부분 수정, 멤버 검증 라이브 버그 3건 (2026-07-20)

사용자가 "로그인부터 전체 게시글/댓글 수집 - 멤버 확인 - 멤버별 댓글수 확인 - 대조까지" 전체
1사이클을 요청해 `BSC_VERIFY_MEMBERS=1`로 3회 실기동했다. §26에서 새로 짠 코드
(`readDisplayedCommentCount`/`expandHiddenReplies` 이중 호출/`collectPerMemberCommentCounts`)가
실제 파이프라인 안에서 두 가지 회귀와 세 가지 새 버그를 드러냈다.

### 27-1. 발견 1: 이벤트버스 중복소비 버그가 재발함(§12-4/§13-1에서 "고쳤다"던 바로 그 버그)

1차 실기동에서 `postsRepliesIncomplete`는 여전히 `[14]`뿐이었지만, `readDisplayedCommentCount`
트레이스(`phase:'readDisplayedCommentCount'`)를 post_no별로 집계하니 **9개 글(23, 31, 32, 33,
43, 45, 46, 47, 48)이 두세 번씩 재처리**되고 있었다(예: post_no=47이 캡처값 47→0→0으로 세 번).

**원인**: 밴드가 같은 post_no에 대해 `get_post`를 두 번 연속 호출하는 경우가 있다(실측:
post_no=48에서 794562ms/795345ms, 800ms 간격으로 emit 두 번). 예전엔
`collectCommentsInOpenModal`이 빨리 끝나서 이 중복 emit이 문제가 안 됐지만, §26에서 추가한
`expandHiddenReplies`(최대 30라운드) + `scrollThroughModal` + `readDisplayedCommentCount`가
처리 시간을 늘리면서, 두 번째 중복 emit이 `walkPostsViaModal`이 "다음 글"을 기다리기 *시작한
뒤에* 버퍼에 도착 - `pendingDetail`의 predicate가 `bandId`만 확인하고 post_no가 실제로
바뀌었는지는 확인 안 해서, 같은 글을 "다음 글"로 착각해 재처리했다.

**1차 수정**: `walkPostsViaModal`의 `pendingDetail` predicate에 `String(e.post.post_no) !==
leavingPostNo` 조건 추가(`acquire/collector.js`).

**2차 실기동 결과**: 9개 → 7개(32, 33, 43, 45, 46, 47, 48)로 줄었지만 **완전히 해결되지
않음**. 47↔48이 번갈아 재등장하는 패턴까지 관찰됨(사용자가 직접 지켜보며 지적) - "바로 직전
글"만 제외하는 것으로는 부족하고, **버퍼에 여러 post_no의 중복 emit이 동시에 남아있어 서로를
오가며 재소비**되는 것으로 보인다. `RECENT_MAX_AGE_MS=60000`(60초) 동안 buffer에 남아있는
모든 stale entry가 잠재적 오염원이다.

**아직 못 고침 - 다음 세션 1순위**: 근본 수정 후보(순서대로 시도):
1. `leavingPostNo` 하나만이 아니라, **이번 walk에서 이미 처리한 post_no 전체 집합**을
   predicate에서 제외(Set으로 누적).
2. 애초에 `expandHiddenReplies`/`readDisplayedCommentCount` 처리 시간 동안 도착하는 중복
   `get_post` emit 자체를 interceptor 단에서 걸러내는 게 더 근본적일 수 있음 - 같은
   post_no의 postDetail이 짧은 시간 내 재emit되면 `interceptor.js`가애초에 두 번째를 버리도록.
3. 데이터 유실 여부 자체는 아직 불명확 - 재처리된 글도 `writer`의 dedup 덕에 raw 파일에
   중복 기록되진 않을 가능성이 높지만(§24-1처럼 writeNewCount=0으로 조용히 무시됐을 수 있음),
   **재처리 도중 두 번째 시도가 진짜 데이터를 못 받아 dedup 인덱스에 없는 답글/댓글을
   놓쳤을 가능성**은 확인 안 됨 - 다음 세션에서 재처리된 post_no들의 최종 raw 데이터가
   `manual_followup` 정답과 맞는지 별도 확인 필요.

### 27-2. 발견 2: `readDisplayedCommentCount`가 항상 "4"만 반환하던 스코프 버그(1차 실기동에서 발견, 수정 완료)

문서 전체에서 `.postCount`를 찾다 보니 모달 뒤 배경 카드 등 무관한 요소를 잘못 집어 어느 글을
열어도 표시값이 "4"로 고정돼 있었다. `.btnCloseLyPost` 기준으로 모달 스코프를 좁히고
`offsetParent !== null`로 화면에 보이는 것만 거르도록 수정(`acquire/collector.js`). **2차
실기동에서 확인**: 표시값이 이제 post마다 다르게 나옴(27, 47, 29, 23, 28...) - 스코프 버그는
해결됨. 다만 이제부터는 표시값과 캡처값의 불일치가 §27-1의 중복처리 버그와 뒤섞여 나타나서,
어느 쪽이 진짜 원인인지 개별 사례마다 분리해서 봐야 한다(예: post_no=47이 한 번은 표시47/
캡처20으로 나왔는데, 47이 §1에서 확인한 정답이므로 이건 "표시값이 맞고 캡처가 실제로 모자란"
경우 - 다만 이 캡처 부족 자체가 §27-1 중복처리의 부작용(두 번째 시도가 처음부터 다시 세다가
중간에 끊김)일 가능성이 높아 보임 - 27-1이 먼저 해결돼야 이 신호도 정확해진다).

### 27-3. 발견 3: 멤버별 댓글 수 검증 - 사용자가 화면을 직접 보며 지적한 라이브 버그 3건

3차 실기동에서 게시글/댓글 수집은 `feedExhausted:true, totalPosts:67, postsCommentsComplete:
51/51`로 끝까지 돌았고, 멤버별 댓글 수 검증 단계로 넘어갔다. 사용자가 화면을 직접 보면서(제가
아니라 사용자가 관찰) 다음 세 가지를 지적했다 - **다음 세션이 실기동 없이도 코드만 보고 바로
고칠 수 있을 만큼 구체적**:

1. **"댓글" 탭 클릭이 안 먹힌다.** "멤버별 작성글 보기" 화면(게시글 탭)에서 "댓글" 탭으로
   전환이 안 되고 계속 게시글 탭에 머물러 있음. `readOneMemberCommentCount`의
   `commentTabClick` 로직(`a.navItem` 중 텍스트가 정확히 "댓글"인 것 찾아 클릭)이 selector는
   §26-5에서 실측 확인됐는데, 실제 자동 실행에서는 클릭이 안 먹히거나 안 찾아지는 것으로
   보임 - `realClickAt`(진짜 마우스 이벤트)을 쓰고 있으니 synthetic click 문제는 아닐 가능성이
   높고, 오히려 §27-3-2와 연결된 타이밍 문제(작성글 보기 페이지가 채 안 뜬 상태에서 "댓글"
   탭을 찾으려다 실패)일 가능성이 크다.
2. **각 단계가 로딩보다 빠르게 진행된다.** 특히 탭 전환처럼 페이지 콘텐츠가 바뀌는 지점은
   `sleep(고정시간)`이 아니라 실제 로딩 완료(예: URL이 기대한 값으로 바뀌었는지, 또는 목표
   요소가 나타났는지)를 확인하고 넘어가야 한다. 사용자 스스로도 "이게 실제로 문제가 되는지는
   모르겠다"고 했지만, §27-3-1과 겹쳐 있을 가능성이 있어 우선순위 높음.
3. **멤버 목록 화면에서 스크롤을 안 한다 - 이게 진짜 원인일 가능성이 가장 높음.**
   `findMemberProfileLinks`는 §26-5에서 "57명이 스크롤 없이도 DOM에 다 있다"는 걸 확인했지만,
   **DOM에 있는 것과 화면(뷰포트) 안에 보이는 것은 다르다.** `getBoundingClientRect()`로 얻은
   좌표는 스크롤 안 된 상태 기준이라, 화면 맨 위 7명(사용자 확인: 김다인까지)을 넘어가는
   멤버는 y좌표가 뷰포트 밖(화면에 안 보이는 아래쪽)을 가리킨다. `realClickAt`은 실제 화면
   좌표에 마우스 이벤트를 주입하므로, 뷰포트 밖 좌표를 클릭하면 아무 것도 안 눌리거나
   엉뚱한 걸 눌러 그 다음부터 "로딩만 계속"되는 것으로 보인다(사용자 관찰과 정확히 일치).
   **수정 방향**: 각 멤버를 클릭하기 직전에 해당 `li`를 `scrollIntoView({block:'center'})`로
   화면 안으로 가져온 뒤, 그 시점에 다시 `getBoundingClientRect()`를 읽어 좌표를 구해야 한다
   (지금은 목록 진입 시 한 번만 좌표를 구해두고 재사용 - 스크롤 후 좌표가 바뀌는 걸 반영 못함).

### 27-4. 다음 세션이 할 일(우선순위순, 세션이 길어져 `/compact` 직전에 정리함)

1. **§27-3-3(멤버 목록 스크롤) 수정 - 가장 확실한 원인.** `readOneMemberCommentCount` 호출
   직전에 해당 멤버의 `li`를 스크롤로 뷰포트 안에 가져오고, 그 즉시 좌표를 다시 읽도록
   `findMemberProfileLinks`/`readOneMemberCommentCount`를 수정. 좌표를 미리 배열로 만들어두는
   지금 방식(`findMemberProfileLinks`가 한 번에 57명 좌표를 다 구함) 대신, 매 멤버 처리
   직전에 이름으로 다시 찾아 스크롤+좌표를 그때그때 구하는 방식으로 바꾸는 게 안전하다.
2. **§27-3-1/2(댓글 탭 전환) 수정.** "작성글 보기" 클릭 후 URL이 `.../post`로 바뀔 때까지
   폴링하고, "댓글" 탭 클릭 후에도 URL이 `.../comment`로 바뀔 때까지 폴링하도록
   `readOneMemberCommentCount`를 수정(지금은 `sleep(1000)` 고정).
3. **§27-1(이벤트버스 중복소비 재발) 근본 수정.** `leavingPostNo` 하나만 제외하는 대신 이번
   walk에서 이미 처리한 post_no 전체 Set을 predicate에서 제외하도록
   `walkPostsViaModal`(`acquire/collector.js`) 수정. 이게 §27-2의 표시값-불일치 신호도
   정확해지게 만드는 선행 조건이다.
4. 위 세 가지를 고친 뒤 `BSC_VERIFY_MEMBERS=1`로 **딱 1회** 재실기동해 전체 사이클(로그인 -
   게시글/댓글 수집 - 멤버 확인 - 멤버별 댓글 수 확인 - 대조)이 끝까지 도는지 확인.
5. 끝까지 되면: (a) `postsRepliesIncomplete`가 여전히 `[14]`뿐인지(§18 답글 펼치기 버튼
   미해결 건), (b) `incomplete_gaps.json`이 §27-1 수정 후에는 지금처럼 50건 넘게 안 뜨고
   실제 결손만 정확히 남는지, (c) `scripts/verify_member_comment_counts.js`로 멤버별 대조
   결과 확인.
6. 여기까지 되면 M1 acquire의 데이터 정확성 검증(§1 최종 합격 테스트 + §26 신뢰도 체계 3단계
   전부)이 끝나고 scoring(M2)으로 넘어갈 수 있다.

## 28. `/compact` 이후 세션(2026-07-20, CLI 새 컨텍스트) — §27-4 세 가지 수정 구현·검증, 멤버
   검증 로직 재설계 2회, 세션 막판 서버 측 제한 의심 신호로 중단

§27-4의 세 가지를 순서대로 구현하고 실기동으로 검증했다(재기동 다수 — 이 세션도 결국
"한 번에 계획해서 최소 재기동" 원칙을 못 지켰다, §28-6 참고).

### 28-1. §27-4 1~3번 구현

- **멤버 목록 스크롤(1순위)**: `findMemberProfileLinkAt(win, index)` 신설 - 인덱스로 해당
  `li`를 찾아 `scrollIntoView({block:'center'})` 후 250ms 대기하고 나서 좌표를 읽는다(기존
  `findMemberProfileLinks`는 한 번에 전부 좌표를 구해 화면 밖 좌표 문제가 있었음).
- **탭 전환 로딩 대기(2순위)**: 새 `pollUntil(win, evalExpr, opts)` 헬퍼로 고정 `sleep` 전부를
  URL 변경/요소 등장 폴링으로 교체.
- **이벤트버스 중복소비(3순위)**: `walkPostsViaModal`에 `seenPostNos`(Set) 추가, `pendingDetail`
  predicate가 "직전 글 post_no 제외"가 아니라 "이번 walk에서 이미 처리한 post_no 전체 제외"로
  강화. **실기동으로 완전 해결 확인**(4차 재확인까지 `clickNextPost` 트레이스 기준 중복 처리
  0건 - §27-1의 재발이 이번엔 완전히 해결됨).

### 28-2. 새 회귀 발견 — 멤버 목록 자체가 지연 로딩이었다(§26-5 기록이 틀렸음)

첫 실기동(4차)에서 멤버별 댓글 수 검증이 "20/30명 확보", "30/57명 확보"로 매번 정확히 30
언저리에서 끊겼다. §27-4에서 만든 `findMemberProfileLinkAt`은 "행이 DOM에 있는지"만 확인했지
"57명이 스크롤 없이 다 렌더링된다"는 §26-5의 전제 자체가 틀렸다는 걸 몰랐다. 사용자가 직접 화면
스크롤로 확인: **30번째 부근에서 스크롤해야 추가 멤버가 로드된다.** 텍스트("초대")로 끝을
판별하지 말라는 사용자 지적(§28-3 참고)에 따라, `ensureMemberRowCount(win, minCount, opts)`를
신설해 "스크롤해도 더 이상 행 수가 안 늘어남"(3회 연속 동일)을 종료 조건으로 썼다(언어 무관,
`scrollWindowToBottom`과 동일 패턴).

### 28-3. 사용자가 스크린샷으로 지적 — "댓글" 탭 전환이 텍스트 매칭 때문에 실패

`readOneMemberCommentCount`가 `a.navItem` 중 텍스트가 정확히 "댓글"인 걸 찾아 클릭했는데,
사용자 스크린샷 확인 결과 **이 세션의 밴드 UI 언어가 영어였다**("Post/Photo/Comment") - 그래서
텍스트가 안 맞아 계속 "Post" 탭에 머물렀다. 사용자는 실사용(한국어)에서만 맞는 텍스트 매칭에
의존하지 말라고 명시적으로 지적("여기서만 영어지 실사용에서는 한국어일 것이니 글자검색은
지양"), 그리고 URL을 직접 조작하는 방법도 제안했다.

**1차 시도(URL 하드 네비게이션)**: `.../post` URL을 `.../comment`로 문자열 치환해
`safeLoadURL`로 직접 이동. 탭 전환 자체는 57/57 성공했지만, `scripts/verify_member_comment_
counts.js`로 대조한 CSV에서 **33명이 표시값 0 또는 정확히 20에서 멈추는 새로운 결손**이
드러났다(예: 남동명 실제 캡처 67개인데 표시값 0, 문설희 실제 31개인데 표시값 20). 하드
리로드가 밴드 SPA의 무한스크롤 로딩 초기화를 깨는 것으로 추정 - **탭 전환 버그를 고치려다
데이터 결손 버그를 새로 만든 사례**, 신뢰도 2단계 교차검증(CLAUDE.md) 자체가 이 사례를
정확히 잡아냈다.

**2차 시도(위치 기반 클릭, 최종 채택)**: 게시글/사진/댓글(Post/Photo/Comment) 탭은 항상 3개
고정 순서이므로, 텍스트 대신 `document.querySelectorAll('a.navItem')`의 **마지막 요소**를
클릭한다 - 언어 무관, 정상 SPA 클릭 네비게이션 유지(무한스크롤 안 깨짐). `scrollWindowToBottom`
에도 `contentSelector` 옵션을 추가해 스크롤 위치뿐 아니라 `a.cCommentOnly` 개수도 안정될 때까지
기다리도록 강화(클릭 직후 첫 배치 비동기 로딩 중 조기 종료 방지).

### 28-4. 사용자 제안 — 멤버 목록을 한 번만 스크롤하고 링크만 타고 들어가면 안 되나?

매 멤버마다 `memberUrl`을 새로 열고 그 인덱스까지 처음부터 재스크롤하는 게 느리고
(§27-3-3을 매번 다시 겪음), 재로드 직후 클릭이 씹히는 것으로 보이는 실패도 있어 사용자가
제안. **`win.webContents.goBack()`으로 시도**: URL 복귀는 정상 확인됐지만(`.../comment` →
`.../post` → `.../member`), **목록 DOM은 그대로 안 남고 0개로 리셋됨**(SPA가 뒤로가기 시
목록 컴포넌트를 재마운트) - "한 번만 스크롤해두면 재사용된다"는 전제는 틀렸다. 최종 설계:
매 인덱스 처리 직전 `ensureMemberRowCount(win, i+1)`로 필요한 만큼만 재스크롤(이미 채워져
있으면 즉시 반환이라 비용 없음) + 실패 시에만 `safeLoadURL`, 성공 시엔 `goBackToMemberList`
(네트워크 왕복 없어 재로드보다 가벼움).

### 28-5. 부수 발견 — `safeLoadURL`의 ERR_ABORTED 판별이 이 환경에서 놓치는 케이스

가벼운 검증용 테스트 스크립트(전체 사이클 대신 특정 멤버 3명만 재현)를 만들다가, 로그인 직후
`win.loadURL()`이 `Error:  (-3) loading '...'`로 reject되는데 **메시지에 "ERR_ABORTED" 텍스트가
없는 경우**를 발견(설명 없이 코드 번호(-3)만). `acquire/collector.js`의 `safeLoadURL`도 같은
정규식을 쓰므로 잠재적으로 같은 문제가 있을 수 있어 방어적으로 `/ERR_ABORTED|\(-3\)/`로
넓혔다.

### 28-6. 최종 검증 — 타겟 3명 성공, 전체 재검증은 서버 측 제한 의심으로 중단

`node_modules/.bin/electron <스크래치 테스트 스크립트>`로 정답이 확정된 멤버 3명만 재현:
**황인각 1/1, 강민지 18/18, 남동명 67/67 - 전부 정확히 일치.** 특히 남동명은 스크롤 중
`a.cCommentOnly` 개수가 0→20→40→60→67로 여러 페이지를 타고 늘어나며 안정화됐다 - §27-3-1의
콘텐츠 안정성 스크롤 수정이 정확히 작동함을 확인.

사용자 승인으로 마지막 전체(`BSC_VERIFY_MEMBERS=1`, 로그인→전체 게시글/댓글→57명 전체) 재검증을
1회 더 시도했으나, 로그인 대기 화면이 완전히 하얗게 멈췄다. 트레이스 확인 결과 `get_env`/
`get_band_information` 요청이 **`status:200`인데 `bodyLen:0`, 응답 시간 12초**로 비정상 - 이
세션에서만 로그인/재기동을 6회 이상 반복한 뒤라, **네이버/밴드 쪽 조용한 요청 제한(soft-block)
가능성**이 있다고 판단해 즉시 프로세스를 종료하고 실기동을 중단했다. CLAUDE.md가 이미 경고한
"실제 anti-abuse 리스크"가 처음으로 관측 가능한 신호를 낸 사례로 기록해둔다.

### 28-7. §28-6 직후 재시도 — 사용자 판단으로 즉시 재시도, 문제없이 57명 전체 스케일 검증 성공

사용자가 §28-6의 soft-block 우려를 "패턴도 없고 그럴 리도 없다"고 판단, 즉시 재시도를
지시했다. 재기동 결과 로그인 페이지가 정상 렌더링(Naver 로그인 폼 스크린샷으로 확인)됐고,
로그인부터 끝까지 정상 완주 - **§28-6의 하얀 화면/12초 지연은 rate-limit이 아니라 일회성
transient 문제였던 것으로 결론**(재현 안 됨, 패턴 없음).

**57명 전체 스케일 최종 검증 결과(성공)**:
- `clickNextPost` 트레이스 기준 중복 처리된 post_no: **0건**(이벤트버스 중복소비 버그 -
  전체 스케일에서도 완전 해결 확인).
- `멤버별 댓글 수 교차검증 완료: 57/57명 확보`(표시값 확보 실패 0명 - §27-3-1/§28-3의
  탭 전환·스크롤 버그 전체 스케일에서도 완전 해결 확인).
- `scripts/verify_member_comment_counts.js` 대조: **불일치 단 2명**(고영빈 +1, 문설희 +1) -
  §28-3에서 봤던 "0 또는 20에서 멈추는" 대량 결손 패턴은 완전히 사라짐. 남은 2건은 이번
  실행에서 게시글 순회가 14건에서 조기 중단된 것과 방향이 일치(부분 수집으로 인한 사소한
  과소, 버그 아님 - 아래 참고).

**같은 실행에서 발견된 별개 이슈(§27-4 범위 밖, 새로 기록)**: 게시글 순회가 "전체 14건"에서
`현재 모달의 게시글 상세(get_post) 캡처를 못 받음`으로 조기 중단됐다(평소 53~61건). §27-1
수정과는 무관 - 재현성 확인 안 된 산발적 타임아웃으로 보임(§18/§27-1과 같은 계열일 수도
있음). 다음 세션에서 반복되면 조사 필요.

### 28-8. 결론 및 다음 세션이 할 일

**§27-4의 세 가지 수정 + §28에서 추가로 발견·수정한 멤버 검증 로직 전체가 57명 실전 스케일로
검증 완료됐다.** M1 acquire의 핵심 데이터 정확성 검증(신뢰도 체계 2단계 교차검증 3종 포함)은
사실상 끝났다고 볼 수 있다.

1. §28-7에서 새로 발견된 "게시글 순회 조기 중단(14건)" 산발적 이슈 - 재현되는지 관찰. 한 번만
   나온 거라 아직 근본 원인 조사할 단계는 아님.
2. 위가 문제없으면 M1 acquire를 완료 선언하고 scoring(M2)으로 넘어갈 수 있다.
3. 코드 변경 사항은 전부 `acquire/collector.js`에 반영돼 있으나 아직 커밋 전이다(사용자가
   명시적으로 커밋을 요청 안 해서 안 함) - `git diff`로 확인 가능. 다음 세션 시작 시 사용자에게
   커밋 여부를 먼저 확인할 것.
